name = "proxy"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

kv_namespaces = [
    # Configure this id to map to the id returned from
    #   wrangler kv:namespace create ai-proxy
    { binding = "ai_proxy", id = "<YOUR_KV_ID>" },
]

[[migrations]]
tag = "v1"                                   # Should be unique for each entry
new_classes = ["PrometheusMetricAggregator"] # Array of new classes

[[migrations]]
tag = "v2" # Migration identifier. This should be unique for each migration entry
deleted_classes = ["PrometheusMetricAggregator"] # Array of deleted class names

[observability.logs]
enabled = true
head_sampling_rate = 0.2

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
# You should not need to edit this
BRAINTRUST_APP_URL = "https://www.braintrust.dev"
METRICS_LICENSE_KEY="<YOUR_METRICS_LICENSE_KEY>"

[env.staging.vars]
BRAINTRUST_APP_URL = "https://www.braintrust.dev"
METRICS_LICENSE_KEY="<YOUR_METRICS_LICENSE_KEY>"

[env.staging]
kv_namespaces = [
    # Configure this id to map to the id returned from
    #   wrangler kv:namespace create ai-proxy
    { binding = "ai_proxy", id = "<YOUR_KV_ID>" },
]

[env.staging.observability]
enabled = true
head_sampling_rate = 1.0 # Sample 100% of staging logs.
