import { z } from "zod";
import type {
  AnyModelParamsType as AnyModelParam,
  ChatCompletionMessageParamType as Message,
  MessageRoleType as MessageRole,
  ModelParamsType as ModelParams,
} from "../src/generated_types";
import {
  ModelFormat,
  ModelEndpointType,
  type ModelName,
  ModelSpec,
  getAvailableModels,
} from "./models";
import { openaiParamsToAnthropicMesssageParams } from "@lib/providers/anthropic";
import { OpenAIChatCompletionCreateParams } from "@types";
import { openaiParamsToGeminiMessageParams } from "@lib/providers/google";

export * from "./secrets";
export * from "./models";
export {
  pcmAudioFormatSchema,
  type PcmAudioFormat,
  mp3BitrateSchema,
  type Mp3Bitrate,
} from "./audio";
export * from "./openai-realtime";

export {
  isImageMediaType,
  isTextBasedMediaType,
  isMediaTypeSupported,
  getSupportedMediaTypes,
  ModelFormatMediaTypes,
  ModelMediaTypeOverrides,
  type TextBasedTextType,
  type ImageMediaType,
} from "./media-types";

export const MessageTypeToMessageType: {
  [messageType in MessageRole]: MessageRole | undefined;
} = {
  system: "system",
  developer: "system",
  function: undefined,
  tool: "tool",
  user: "user",
  assistant: "assistant",
  model: "assistant",
};

export const modelParamToModelParam: {
  [name: string]: keyof AnyModelParam | null;
} = {
  temperature: "temperature",
  top_p: "top_p",
  top_k: "top_k",
  max_tokens: "max_tokens",
  max_tokens_to_sample: null,
  use_cache: "use_cache",
  maxOutputTokens: "max_tokens",
  topP: "top_p",
  topK: "top_k",
  presence_penalty: null,
  frequency_penalty: null,
  user: null,
  function_call: null,
  n: null,
  logprobs: null,
  stream_options: null,
  parallel_tool_calls: null,
  response_format: null,
  reasoning_effort: "reasoning_effort",
  reasoning_enabled: "reasoning_enabled",
  reasoning_budget: "reasoning_budget",
  verbosity: "verbosity",
  stop: null,
};

const paramMappers: Partial<
  Record<
    ModelFormat,
    (
      params: OpenAIChatCompletionCreateParams,
      modelSpec?: ModelSpec | null,
    ) => object
  >
> = {
  anthropic: openaiParamsToAnthropicMesssageParams,
  google: openaiParamsToGeminiMessageParams,
};

export const sliderSpecs: {
  // min, max, step, required
  [name: string]: [number, number, number, boolean];
} = {
  temperature: [0, 2, 0.01, false],
  top_p: [0, 1, 0.01, false],
  topP: [0, 1, 0.01, false],
  max_tokens: [1, 32768, 1, false],
  maxOutputTokens: [1, 32768, 1, true],
  frequency_penalty: [0, 1, 0.01, false],
  presence_penalty: [0, 1, 0.01, false],
  top_k: [1, 100, 1, false],
  topK: [1, 100, 1, false],
};

// Format-specific slider specification overrides
const formatSpecificSliderSpecs: {
  [format in ModelFormat]?: {
    [paramName: string]: [number, number, number, boolean];
  };
} = {
  anthropic: {
    temperature: [0, 1, 0.01, false],
  },
  converse: {
    temperature: [0, 1, 0.01, false],
  },
};

/**
 * Get slider specifications for a parameter, with format-specific overrides
 * @param format - The model format (openai, anthropic, google, etc.)
 * @param paramName - The parameter name (temperature, max_tokens, etc.)
 * @returns Slider spec as [min, max, step, required] or undefined if not found
 */
export function getSliderSpecs(
  format: ModelFormat,
  paramName: string,
): [number, number, number, boolean] | undefined {
  const formatOverrides = formatSpecificSliderSpecs[format];
  if (formatOverrides && formatOverrides[paramName]) {
    return formatOverrides[paramName];
  }

  return sliderSpecs[paramName];
}

// These values resemble the default values in OpenAI's playground and Anthropic's docs.
// Even though some of them are not set, it's useful for the "greyed out" placeholders.
export const defaultModelParamSettings: {
  [name in ModelFormat]: ModelParams;
} = {
  openai: {
    temperature: undefined,
    max_tokens: undefined,
    top_p: undefined,
    frequency_penalty: 0,
    presence_penalty: 0,
    response_format: null,
    stop: undefined,
    use_cache: true,
    reasoning_effort: "medium",
    verbosity: "medium",
  },
  anthropic: {
    temperature: undefined,
    max_tokens: undefined,
    top_p: undefined,
    top_k: undefined,
    use_cache: true,
    reasoning_enabled: false,
    reasoning_budget: undefined,
    verbosity: undefined,
  },
  google: {
    temperature: undefined,
    maxOutputTokens: undefined,
    topP: undefined,
    topK: undefined,
    use_cache: true,
    reasoning_enabled: false,
    reasoning_budget: undefined,
    verbosity: undefined,
  },
  js: {},
  window: {
    temperature: undefined,
    topK: 5,
  },
  converse: {
    temperature: undefined,
    max_tokens: undefined,
    top_p: undefined,
    use_cache: true,
  },
};

export const modelProviderHasTools: {
  [name in ModelFormat]: boolean;
} = {
  openai: true,
  anthropic: true,
  google: true,
  js: false,
  window: false,
  converse: true,
};

export const modelProviderHasReasoning: {
  [name in ModelFormat]?: RegExp;
} = {
  openai: /^(o[1-4])|(gpt-5)/i,
  anthropic: /^claude-3\.7/i,
  google: /gemini-2.0-flash$|gemini-2.5/i,
  js: undefined,
  window: undefined,
  converse: undefined,
};

export const DefaultEndpointTypes: {
  [name in ModelFormat]: ModelEndpointType[];
} = {
  openai: ["openai", "azure"],
  anthropic: ["anthropic"],
  google: ["google"],
  js: ["js"],
  window: ["js"],
  converse: ["bedrock"],
};

export const AvailableEndpointTypes: { [name: string]: ModelEndpointType[] } = {
  "gpt-35-turbo": ["azure"],
  "gpt-35-turbo-16k": ["azure"],
  sonar: ["perplexity"],
  "sonar-pro": ["perplexity"],
  "sonar-reasoning": ["perplexity"],
  "sonar-reasoning-pro": ["perplexity"],
  "r1-1776": ["perplexity"],
  "meta/llama-2-70b-chat": ["replicate"],
  "mistralai/Mistral-7B-Instruct-v0.1": ["together"],
  "mistralai/Mixtral-8x22B": ["together"],
  "mistralai/Mixtral-8x22B-Instruct-v0.1": ["together"],
  "mistralai/mixtral-8x7b-32kseqlen": ["together"],
  "mistralai/Mixtral-8x7B-Instruct-v0.1": ["together"],
  "mistralai/Mixtral-8x7B-Instruct-v0.1-json": ["together"],
  "mistralai/Mistral-Small-24B-Instruct-2501": ["together"],
  "mistralai/Mistral-7B-Instruct-v0.3": ["together"],
  "mistralai/Mistral-7B-Instruct-v0.2": ["together"],
  "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8": ["together"],
  "meta-llama/Llama-4-Scout-17B-16E-Instruct": ["together"],
  "meta-llama/Llama-2-70b-chat-hf": ["together"],
  "meta-llama/Meta-Llama-3-70B": ["together"],
  "meta-llama/Llama-3-70b-chat-hf": ["together"],
  "meta-llama/Llama-3-8b-hf": ["together"],
  "meta-llama/Llama-3-8b-chat-hf": ["together"],
  "meta-llama/Llama-3.2-3B-Instruct-Turbo": ["together"],
  "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo": ["together"],
  "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo": ["together"],
  "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo": ["together"],
  "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo": ["together"],
  "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo": ["together"],
  "NousResearch/Nous-Hermes-2-Yi-34B": ["together"],
  "deepseek-ai/deepseek-coder-33b-instruct": ["together"],
  "meta-llama/Llama-3.3-70B-Instruct-Turbo": ["together"],
  "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free": ["together"],
  "meta-llama/Llama-Vision-Free": ["together"],
  "meta-llama/Meta-Llama-3-70B-Instruct-Turbo": ["together"],
  "meta-llama/Meta-Llama-3-70B-Instruct-Lite": ["together"],
  "meta-llama/Meta-Llama-3-8B-Instruct-Turbo": ["together"],
  "meta-llama/Meta-Llama-3-8B-Instruct-Lite": ["together"],
  "deepseek-ai/DeepSeek-V3": ["together"],
  "deepseek-ai/DeepSeek-R1": ["together"],
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B": ["together"],
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B-Free": ["together"],
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": ["together"],
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B": ["together"],
  "deepseek-ai/deepseek-llm-67b-chat": ["together"],
  "Qwen/Qwen2.5-72B-Instruct-Turbo": ["together"],
  "Qwen/Qwen2.5-7B-Instruct-Turbo": ["together"],
  "Qwen/Qwen2.5-Coder-32B-Instruct": ["together"],
  "Qwen/QwQ-32B-Preview": ["together"],
  "Qwen/QwQ-32B": ["together"],
  "Qwen/Qwen2-VL-72B-Instruct": ["together"],
  "Qwen/Qwen2-72B-Instruct": ["together"],
  "google/gemma-2-27b-it": ["together"],
  "google/gemma-2-9b-it": ["together"],
  "google/gemma-2b-it": ["together"],
  "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF": ["together"],
  "microsoft/WizardLM-2-8x22B": ["together"],
  "databricks/dbrx-instruct": ["together"],
  "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO": ["together"],
  "Gryphe/MythoMax-L2-13b": ["together"],
  "Gryphe/MythoMax-L2-13b-Lite": ["together"],
  "magistral-medium-latest": ["mistral"],
  "magistral-medium-2506": ["mistral"],
  "magistral-small-latest": ["mistral"],
  "magistral-small-2506": ["mistral"],
  "devstral-small-latest": ["mistral"],
  "devstral-small-2507": ["mistral"],
  "mistral-large-latest": ["mistral"],
  "open-mistral-nemo": ["mistral"],
  "codestral-latest": ["mistral"],
  "open-mixtral-8x22b": ["mistral"],
  "open-codestral-mamba": ["mistral"],
  "mistral-saba-latest": ["mistral"],
  "mistral-saba-2502": ["mistral"],
  "mistral-tiny": ["mistral"],
  "mistral-small": ["mistral"],
  "mistral-medium": ["mistral"],
  "pixtral-12b-2409": ["mistral"],
  "mistral-large-2411": ["mistral"],
  "pixtral-large-latest": ["mistral"],
  "mistral-medium-latest": ["mistral"],
  "mistral-medium-2505": ["mistral"],
  "pixtral-large-2411": ["mistral", "vertex"],
  "mistral-small-latest": ["mistral"],
  "mistral-small-2501": ["mistral"],
  "codestral-2501": ["mistral"],
  "ministral-8b-latest": ["mistral"],
  "ministral-8b-2410": ["mistral"],
  "ministral-3b-latest": ["mistral"],
  "ministral-3b-2410": ["mistral"],
  "open-mistral-nemo-2407": ["mistral"],
  mistral: ["ollama"],
  phi: ["ollama"],
  "meta-llama/llama-4-maverick-17b-128e-instruct": ["groq"],
  "meta-llama/llama-4-scout-17b-16e-instruct": ["groq"],
  "llama-3.3-70b-versatile": ["groq"],
  "llama-3.1-8b-instant": ["groq"],
  "llama-3.1-70b-versatile": ["groq"],
  "llama-3.1-405b-reasoning": ["groq"],
  "llama3-8b-8192": ["groq"],
  "llama3-70b-8192": ["groq"],
  "llama2-70b-4096": ["groq"],
  "mistral-saba-24b": ["groq"],
  "mixtral-8x7b-32768": ["groq"],
  "gemma-7b-it": ["groq"],
  "deepseek-r1-distill-llama-70b": ["groq", "cerebras"],
  "gemma2-9b-it": ["groq"],
  "llama-3.3-70b-specdec": ["groq"],
  "llama-3.2-90b-vision-preview": ["groq"],
  "llama-3.2-11b-vision-preview": ["groq"],
  "llama-3.2-3b-preview": ["groq"],
  "llama-3.2-1b-preview": ["groq"],
  "llama-guard-3-8b": ["groq"],
  "deepseek-r1-distill-llama-70b-specdec": ["groq"],
  "deepseek-r1-distill-qwen-32b": ["groq"],
  "qwen/qwen3-32b": ["groq"],
  "moonshotai/kimi-k2-instruct-0905": ["groq"],
  "qwen-2.5-32b": ["groq"],
  "qwen-2.5-coder-32b": ["groq"],
  "qwen-qwq-32b": ["groq"],
  "llama3-3-70b": ["lepton"],
  "llama3-2-3b": ["lepton"],
  "llama3-2-1b": ["lepton"],
  "llama3-1-70b": ["lepton"],
  "llama3-1-8b": ["lepton"],
  "llama3-70b": ["lepton"],
  "llama3-8b": ["lepton"],
  "mistral-7b": ["lepton"],
  "mixtral-8x7b": ["lepton"],
  "wizardlm-2-7b": ["lepton"],
  "wizardlm-2-8x22b": ["lepton"],
  "nous-hermes-llama2-13b": ["lepton"],
  "dolphin-mixtral-8x7b": ["lepton"],
  "llama-4-scout-17b-16e-instruct": ["cerebras"],
  "llama3.1-8b": ["cerebras"],
  "llama3.3-70b": ["cerebras"],
  "accounts/fireworks/models/llama4-maverick-instruct-basic": ["fireworks"],
  "accounts/fireworks/models/llama4-scout-instruct-basic": ["fireworks"],
  "accounts/fireworks/models/llama-v3p3-70b-instruct": ["fireworks"],
  "accounts/fireworks/models/llama-v3p2-3b-instruct": ["fireworks"],
  "accounts/fireworks/models/llama-v3p1-8b-instruct": ["fireworks"],
  "accounts/fireworks/models/llama-v3p2-11b-vision-instruct": ["fireworks"],
  "accounts/fireworks/models/llama-v3p1-70b-instruct": ["fireworks"],
  "accounts/fireworks/models/llama-v3p2-90b-vision-instruct": ["fireworks"],
  "accounts/fireworks/models/llama-v3p1-405b-instruct": ["fireworks"],
  "accounts/fireworks/models/qwen2p5-coder-32b-instruct": ["fireworks"],
  "accounts/fireworks/models/mixtral-8x22b-instruct": ["fireworks"],
  "accounts/fireworks/models/deepseek-v3": ["fireworks"],
  "accounts/fireworks/models/deepseek-v3-0324": ["fireworks"],
  "accounts/fireworks/models/deepseek-r1": ["fireworks"],
  "accounts/fireworks/models/deepseek-r1-basic": ["fireworks"],
  "accounts/fireworks/models/llama-v3p1-405b-instruct-long": ["fireworks"],
  "accounts/fireworks/models/qwen2p5-72b-instruct": ["fireworks"],
  "accounts/fireworks/models/qwen-qwq-32b-preview": ["fireworks"],
  "accounts/fireworks/models/qwq-32b": ["fireworks"],
  "accounts/fireworks/models/qwen2-vl-72b-instruct": ["fireworks"],
  "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct": ["fireworks"],
  "accounts/fireworks/models/qwen3-235b-a22b": ["fireworks"],
  "accounts/fireworks/models/qwen3-235b-a22b-instruct-2507": ["fireworks"],
  "accounts/fireworks/models/qwen3-30b-a3b": ["fireworks"],
  "accounts/fireworks/models/deepseek-v3p2": ["fireworks"],
  "accounts/fireworks/models/kimi-k2-thinking": ["fireworks"],
  "accounts/fireworks/models/mistral-small-24b-instruct-2501": ["fireworks"],
  "accounts/fireworks/models/mixtral-8x7b-instruct": ["fireworks"],
  "accounts/fireworks/models/phi-3-vision-128k-instruct": ["fireworks"],
  "anthropic.claude-sonnet-4-6": ["bedrock"],
  "us.anthropic.claude-sonnet-4-6": ["bedrock"],
  "anthropic.claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "us.anthropic.claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "anthropic.claude-sonnet-4-20250514-v1:0": ["bedrock"],
  "us.anthropic.claude-sonnet-4-20250514-v1:0": ["bedrock"],
  "anthropic.claude-3-7-sonnet-20250219-v1:0": ["bedrock"],
  "us.anthropic.claude-3-7-sonnet-20250219-v1:0": ["bedrock"],
  "anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "us.anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "anthropic.claude-3-5-haiku-20241022-v1:0": ["bedrock"],
  "us.anthropic.claude-3-5-haiku-20241022-v1:0": ["bedrock"],
  "anthropic.claude-3-5-sonnet-20241022-v2:0": ["bedrock"],
  "us.anthropic.claude-3-5-sonnet-20241022-v2:0": ["bedrock"],
  "apac.anthropic.claude-3-5-sonnet-20241022-v2:0": ["bedrock"],
  "anthropic.claude-3-5-sonnet-20240620-v1:0": ["bedrock"],
  "us.anthropic.claude-3-5-sonnet-20240620-v1:0": ["bedrock"],
  "apac.anthropic.claude-3-5-sonnet-20240620-v1:0": ["bedrock"],
  "eu.anthropic.claude-3-5-sonnet-20240620-v1:0": ["bedrock"],
  "anthropic.claude-opus-4-20250514-v1:0": ["bedrock"],
  "us.anthropic.claude-opus-4-20250514-v1:0": ["bedrock"],
  "anthropic.claude-3-opus-20240229-v1:0": ["bedrock"],
  "us.anthropic.claude-3-opus-20240229-v1:0": ["bedrock"],
  "anthropic.claude-3-sonnet-20240229-v1:0": ["bedrock"],
  "us.anthropic.claude-3-sonnet-20240229-v1:0": ["bedrock"],
  "apac.anthropic.claude-3-sonnet-20240229-v1:0": ["bedrock"],
  "eu.anthropic.claude-3-sonnet-20240229-v1:0": ["bedrock"],
  "anthropic.claude-3-haiku-20240307-v1:0": ["bedrock"],
  "us.anthropic.claude-3-haiku-20240307-v1:0": ["bedrock"],
  "apac.anthropic.claude-3-haiku-20240307-v1:0": ["bedrock"],
  "eu.anthropic.claude-3-haiku-20240307-v1:0": ["bedrock"],
  "anthropic.claude-opus-4-5-20251101-v1:0": ["bedrock"],
  "us.anthropic.claude-opus-4-5-20251101-v1:0": ["bedrock"],
  "anthropic.claude-opus-4-7": ["bedrock"],
  "anthropic.claude-opus-4-6-v1:0": ["bedrock"],
  "us.anthropic.claude-opus-4-6-v1:0": ["bedrock"],
  "anthropic.claude-opus-4-1-20250805-v1:0": ["bedrock"],
  "us.anthropic.claude-opus-4-1-20250805-v1:0": ["bedrock"],
  "amazon.nova-pro-v1:0": ["bedrock"],
  "amazon.nova-lite-v1:0": ["bedrock"],
  "amazon.nova-micro-v1:0": ["bedrock"],
  "grok-4-1-fast": ["xAI"],
  "grok-4-1-fast-reasoning": ["xAI"],
  "grok-4-1-fast-reasoning-latest": ["xAI"],
  "grok-4-1-fast-non-reasoning": ["xAI"],
  "grok-4-1-fast-non-reasoning-latest": ["xAI"],
  "grok-4-fast-reasoning": ["xAI"],
  "grok-4-fast-reasoning-latest": ["xAI"],
  "grok-4-fast-non-reasoning": ["xAI"],
  "grok-4-fast-non-reasoning-latest": ["xAI"],
  "grok-4": ["xAI"],
  "grok-4-latest": ["xAI"],
  "grok-4-0709": ["xAI"],
  "grok-2-vision": ["xAI"],
  "grok-2-vision-latest": ["xAI"],
  "grok-2-vision-1212": ["xAI"],
  "grok-2": ["xAI"],
  "grok-2-latest": ["xAI"],
  "grok-2-1212": ["xAI"],
  "grok-vision-beta": ["xAI"],
  "grok-beta": ["xAI"],
  "claude-opus-4-1": ["anthropic"],
  "claude-opus-4-6-20260205": ["anthropic"],
  "claude-opus-4-7-20260416": ["anthropic"],
  "baseten/deepseek-ai/DeepSeek-V3-0324": ["baseten"],
  "baseten/deepseek-ai/DeepSeek-V3.1": ["baseten"],
  "baseten/MiniMaxAI/MiniMax-M2.5": ["baseten"],
  "baseten/moonshotai/Kimi-K2-Instruct-0905": ["baseten"],
  "baseten/moonshotai/Kimi-K2-Thinking": ["baseten"],
  "baseten/moonshotai/Kimi-K2.5": ["baseten"],
  "baseten/nvidia/Nemotron-120B-A12B": ["baseten"],
  "baseten/openai/gpt-oss-120b": ["baseten"],
  "baseten/zai-org/GLM-4.6": ["baseten"],
  "baseten/zai-org/GLM-4.7": ["baseten"],
  "baseten/zai-org/GLM-5": ["baseten"],
  "1024-x-1024/50-steps/bedrock/amazon.nova-canvas-v1:0": ["bedrock"],
  "1024-x-1024/50-steps/stability.stable-diffusion-xl-v1": ["bedrock"],
  "1024-x-1024/max-steps/stability.stable-diffusion-xl-v1": ["bedrock"],
  "512-x-512/50-steps/stability.stable-diffusion-xl-v0": ["bedrock"],
  "512-x-512/max-steps/stability.stable-diffusion-xl-v0": ["bedrock"],
  "ai21.j2-mid-v1": ["bedrock"],
  "ai21.j2-ultra-v1": ["bedrock"],
  "ai21.jamba-1-5-large-v1:0": ["bedrock"],
  "ai21.jamba-1-5-mini-v1:0": ["bedrock"],
  "ai21.jamba-instruct-v1:0": ["bedrock"],
  "amazon.nova-2-multimodal-embeddings-v1:0": ["bedrock"],
  "amazon.nova-canvas-v1:0": ["bedrock"],
  "amazon.rerank-v1:0": ["bedrock"],
  "amazon.titan-embed-image-v1": ["bedrock"],
  "amazon.titan-embed-text-v1": ["bedrock"],
  "amazon.titan-embed-text-v2:0": ["bedrock"],
  "amazon.titan-image-generator-v1": ["bedrock"],
  "amazon.titan-image-generator-v2": ["bedrock"],
  "amazon.titan-image-generator-v2:0": ["bedrock"],
  "anthropic.claude-3-7-sonnet-20240620-v1:0": ["bedrock"],
  "anthropic.claude-instant-v1": ["bedrock"],
  "anthropic.claude-v1": ["bedrock"],
  "anthropic.claude-v2:1": ["bedrock"],
  "bedrock/*/1-month-commitment/cohere.command-light-text-v14": ["bedrock"],
  "bedrock/*/1-month-commitment/cohere.command-text-v14": ["bedrock"],
  "bedrock/*/6-month-commitment/cohere.command-light-text-v14": ["bedrock"],
  "bedrock/*/6-month-commitment/cohere.command-text-v14": ["bedrock"],
  "bedrock/ap-northeast-1/1-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/ap-northeast-1/1-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/ap-northeast-1/1-month-commitment/anthropic.claude-v2:1": [
    "bedrock",
  ],
  "bedrock/ap-northeast-1/6-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/ap-northeast-1/6-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/ap-northeast-1/6-month-commitment/anthropic.claude-v2:1": [
    "bedrock",
  ],
  "bedrock/ap-northeast-1/anthropic.claude-instant-v1": ["bedrock"],
  "bedrock/ap-northeast-1/anthropic.claude-v1": ["bedrock"],
  "bedrock/ap-northeast-1/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/ap-northeast-1/deepseek.v3.2": ["bedrock"],
  "bedrock/ap-northeast-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/ap-northeast-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/ap-northeast-1/moonshotai.kimi-k2-thinking": ["bedrock"],
  "bedrock/ap-northeast-1/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/ap-northeast-1/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/ap-south-1/deepseek.v3.2": ["bedrock"],
  "bedrock/ap-south-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/ap-south-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/ap-south-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/ap-south-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/ap-south-1/moonshotai.kimi-k2-thinking": ["bedrock"],
  "bedrock/ap-south-1/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/ap-south-1/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/ap-southeast-2/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/ap-southeast-3/deepseek.v3.2": ["bedrock"],
  "bedrock/ap-southeast-3/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/ap-southeast-3/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/ap-southeast-3/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/ap-southeast-3/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/ca-central-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/ca-central-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/eu-central-1/1-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/eu-central-1/1-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/eu-central-1/1-month-commitment/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/eu-central-1/6-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/eu-central-1/6-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/eu-central-1/6-month-commitment/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/eu-central-1/anthropic.claude-instant-v1": ["bedrock"],
  "bedrock/eu-central-1/anthropic.claude-v1": ["bedrock"],
  "bedrock/eu-central-1/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/eu-central-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/eu-central-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/eu-central-1/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/eu-north-1/deepseek.v3.2": ["bedrock"],
  "bedrock/eu-north-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/eu-north-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/eu-north-1/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/eu-south-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/eu-south-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/eu-south-1/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/eu-west-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/eu-west-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/eu-west-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/eu-west-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/eu-west-1/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/eu-west-2/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/eu-west-2/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/eu-west-2/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/eu-west-2/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/eu-west-2/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/eu-west-3/mistral.mistral-7b-instruct-v0:2": ["bedrock"],
  "bedrock/eu-west-3/mistral.mistral-large-2402-v1:0": ["bedrock"],
  "bedrock/eu-west-3/mistral.mixtral-8x7b-instruct-v0:1": ["bedrock"],
  "bedrock/invoke/anthropic.claude-3-5-sonnet-20240620-v1:0": ["bedrock"],
  "bedrock/moonshotai.kimi-k2-thinking": ["bedrock"],
  "bedrock/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/sa-east-1/deepseek.v3.2": ["bedrock"],
  "bedrock/sa-east-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/sa-east-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/sa-east-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/sa-east-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/sa-east-1/moonshotai.kimi-k2-thinking": ["bedrock"],
  "bedrock/sa-east-1/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/sa-east-1/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/us-east-1/1-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/us-east-1/1-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/us-east-1/1-month-commitment/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/us-east-1/6-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/us-east-1/6-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/us-east-1/6-month-commitment/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/us-east-1/anthropic.claude-instant-v1": ["bedrock"],
  "bedrock/us-east-1/anthropic.claude-v1": ["bedrock"],
  "bedrock/us-east-1/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/us-east-1/deepseek.v3.2": ["bedrock"],
  "bedrock/us-east-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/us-east-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/us-east-1/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/us-east-1/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/us-east-1/mistral.mistral-7b-instruct-v0:2": ["bedrock"],
  "bedrock/us-east-1/mistral.mistral-large-2402-v1:0": ["bedrock"],
  "bedrock/us-east-1/mistral.mixtral-8x7b-instruct-v0:1": ["bedrock"],
  "bedrock/us-east-1/moonshotai.kimi-k2-thinking": ["bedrock"],
  "bedrock/us-east-1/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/us-east-1/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/us-east-2/deepseek.v3.2": ["bedrock"],
  "bedrock/us-east-2/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/us-east-2/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/us-east-2/moonshotai.kimi-k2-thinking": ["bedrock"],
  "bedrock/us-east-2/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/us-east-2/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/us-gov-east-1/amazon.nova-pro-v1:0": ["bedrock"],
  "bedrock/us-gov-east-1/amazon.titan-embed-text-v1": ["bedrock"],
  "bedrock/us-gov-east-1/amazon.titan-embed-text-v2:0": ["bedrock"],
  "bedrock/us-gov-east-1/amazon.titan-text-express-v1": ["bedrock"],
  "bedrock/us-gov-east-1/amazon.titan-text-lite-v1": ["bedrock"],
  "bedrock/us-gov-east-1/amazon.titan-text-premier-v1:0": ["bedrock"],
  "bedrock/us-gov-east-1/anthropic.claude-3-5-sonnet-20240620-v1:0": [
    "bedrock",
  ],
  "bedrock/us-gov-east-1/anthropic.claude-3-haiku-20240307-v1:0": ["bedrock"],
  "bedrock/us-gov-east-1/anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "bedrock/us-gov-east-1/anthropic.claude-sonnet-4-5-20250929-v1:0": [
    "bedrock",
  ],
  "bedrock/us-gov-east-1/claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "bedrock/us-gov-east-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/us-gov-east-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/us-gov-west-1/amazon.nova-pro-v1:0": ["bedrock"],
  "bedrock/us-gov-west-1/amazon.titan-embed-text-v1": ["bedrock"],
  "bedrock/us-gov-west-1/amazon.titan-embed-text-v2:0": ["bedrock"],
  "bedrock/us-gov-west-1/amazon.titan-text-express-v1": ["bedrock"],
  "bedrock/us-gov-west-1/amazon.titan-text-lite-v1": ["bedrock"],
  "bedrock/us-gov-west-1/amazon.titan-text-premier-v1:0": ["bedrock"],
  "bedrock/us-gov-west-1/anthropic.claude-3-5-sonnet-20240620-v1:0": [
    "bedrock",
  ],
  "bedrock/us-gov-west-1/anthropic.claude-3-7-sonnet-20250219-v1:0": [
    "bedrock",
  ],
  "bedrock/us-gov-west-1/anthropic.claude-3-haiku-20240307-v1:0": ["bedrock"],
  "bedrock/us-gov-west-1/anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "bedrock/us-gov-west-1/anthropic.claude-sonnet-4-5-20250929-v1:0": [
    "bedrock",
  ],
  "bedrock/us-gov-west-1/claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "bedrock/us-gov-west-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/us-gov-west-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/us-west-1/meta.llama3-70b-instruct-v1:0": ["bedrock"],
  "bedrock/us-west-1/meta.llama3-8b-instruct-v1:0": ["bedrock"],
  "bedrock/us-west-2/1-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/us-west-2/1-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/us-west-2/1-month-commitment/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/us-west-2/6-month-commitment/anthropic.claude-instant-v1": [
    "bedrock",
  ],
  "bedrock/us-west-2/6-month-commitment/anthropic.claude-v1": ["bedrock"],
  "bedrock/us-west-2/6-month-commitment/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/us-west-2/anthropic.claude-instant-v1": ["bedrock"],
  "bedrock/us-west-2/anthropic.claude-v1": ["bedrock"],
  "bedrock/us-west-2/anthropic.claude-v2:1": ["bedrock"],
  "bedrock/us-west-2/deepseek.v3.2": ["bedrock"],
  "bedrock/us-west-2/minimax.minimax-m2.1": ["bedrock"],
  "bedrock/us-west-2/minimax.minimax-m2.5": ["bedrock"],
  "bedrock/us-west-2/mistral.mistral-7b-instruct-v0:2": ["bedrock"],
  "bedrock/us-west-2/mistral.mistral-large-2402-v1:0": ["bedrock"],
  "bedrock/us-west-2/mistral.mixtral-8x7b-instruct-v0:1": ["bedrock"],
  "bedrock/us-west-2/moonshotai.kimi-k2-thinking": ["bedrock"],
  "bedrock/us-west-2/moonshotai.kimi-k2.5": ["bedrock"],
  "bedrock/us-west-2/qwen.qwen3-coder-next": ["bedrock"],
  "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0": ["bedrock"],
  "claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "cohere.embed-english-v3": ["bedrock"],
  "cohere.embed-multilingual-v3": ["bedrock"],
  "cohere.embed-v4:0": ["bedrock"],
  "cohere.rerank-v3-5:0": ["bedrock"],
  "eu.anthropic.claude-3-5-haiku-20241022-v1:0": ["bedrock"],
  "eu.anthropic.claude-3-5-sonnet-20241022-v2:0": ["bedrock"],
  "eu.anthropic.claude-3-7-sonnet-20250219-v1:0": ["bedrock"],
  "eu.anthropic.claude-3-opus-20240229-v1:0": ["bedrock"],
  "eu.twelvelabs.marengo-embed-2-7-v1:0": ["bedrock"],
  "eu.twelvelabs.pegasus-1-2-v1:0": ["bedrock"],
  "max-x-max/50-steps/stability.stable-diffusion-xl-v0": ["bedrock"],
  "max-x-max/max-steps/stability.stable-diffusion-xl-v0": ["bedrock"],
  "meta.llama2-13b-chat-v1": ["bedrock"],
  "meta.llama2-70b-chat-v1": ["bedrock"],
  "mistral.mistral-large-2407-v1:0": ["bedrock"],
  "stability.sd3-5-large-v1:0": ["bedrock"],
  "stability.sd3-large-v1:0": ["bedrock"],
  "stability.stable-conservative-upscale-v1:0": ["bedrock"],
  "stability.stable-creative-upscale-v1:0": ["bedrock"],
  "stability.stable-fast-upscale-v1:0": ["bedrock"],
  "stability.stable-image-control-sketch-v1:0": ["bedrock"],
  "stability.stable-image-control-structure-v1:0": ["bedrock"],
  "stability.stable-image-core-v1:0": ["bedrock"],
  "stability.stable-image-core-v1:1": ["bedrock"],
  "stability.stable-image-erase-object-v1:0": ["bedrock"],
  "stability.stable-image-inpaint-v1:0": ["bedrock"],
  "stability.stable-image-remove-background-v1:0": ["bedrock"],
  "stability.stable-image-search-recolor-v1:0": ["bedrock"],
  "stability.stable-image-search-replace-v1:0": ["bedrock"],
  "stability.stable-image-style-guide-v1:0": ["bedrock"],
  "stability.stable-image-ultra-v1:0": ["bedrock"],
  "stability.stable-image-ultra-v1:1": ["bedrock"],
  "stability.stable-outpaint-v1:0": ["bedrock"],
  "stability.stable-style-transfer-v1:0": ["bedrock"],
  "twelvelabs.marengo-embed-2-7-v1:0": ["bedrock"],
  "twelvelabs.pegasus-1-2-v1:0": ["bedrock"],
  "us.amazon.nova-canvas-v1:0": ["bedrock"],
  "us.twelvelabs.marengo-embed-2-7-v1:0": ["bedrock"],
  "us.twelvelabs.pegasus-1-2-v1:0": ["bedrock"],
  "amazon.nova-2-lite-v1:0": ["bedrock"],
  "amazon.nova-2-pro-preview-20251202-v1:0": ["bedrock"],
  "anthropic.claude-haiku-4-5@20251001": ["bedrock"],
  "anthropic.claude-opus-4-6-v1": ["bedrock"],
  "apac.amazon.nova-2-lite-v1:0": ["bedrock"],
  "apac.amazon.nova-2-pro-preview-20251202-v1:0": ["bedrock"],
  "apac.amazon.nova-lite-v1:0": ["bedrock"],
  "apac.amazon.nova-micro-v1:0": ["bedrock"],
  "apac.amazon.nova-pro-v1:0": ["bedrock"],
  "apac.anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "apac.anthropic.claude-sonnet-4-20250514-v1:0": ["bedrock"],
  "au.anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "au.anthropic.claude-opus-4-6-v1": ["bedrock"],
  "au.anthropic.claude-opus-4-7": ["bedrock"],
  "au.anthropic.claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "au.anthropic.claude-sonnet-4-6": ["bedrock"],
  "deepseek.v3-v1:0": ["bedrock"],
  "deepseek.v3.2": ["bedrock"],
  "eu.amazon.nova-2-lite-v1:0": ["bedrock"],
  "eu.amazon.nova-2-pro-preview-20251202-v1:0": ["bedrock"],
  "eu.amazon.nova-lite-v1:0": ["bedrock"],
  "eu.amazon.nova-micro-v1:0": ["bedrock"],
  "eu.amazon.nova-pro-v1:0": ["bedrock"],
  "eu.anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "eu.anthropic.claude-opus-4-1-20250805-v1:0": ["bedrock"],
  "eu.anthropic.claude-opus-4-20250514-v1:0": ["bedrock"],
  "eu.anthropic.claude-opus-4-5-20251101-v1:0": ["bedrock"],
  "eu.anthropic.claude-opus-4-6-v1": ["bedrock"],
  "eu.anthropic.claude-opus-4-7": ["bedrock"],
  "eu.anthropic.claude-sonnet-4-20250514-v1:0": ["bedrock"],
  "eu.anthropic.claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "eu.anthropic.claude-sonnet-4-6": ["bedrock"],
  "eu.deepseek.v3.2": ["bedrock"],
  "eu.mistral.pixtral-large-2502-v1:0": ["bedrock"],
  "global.amazon.nova-2-lite-v1:0": ["bedrock"],
  "global.anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "global.anthropic.claude-opus-4-5-20251101-v1:0": ["bedrock"],
  "global.anthropic.claude-opus-4-6-v1": ["bedrock"],
  "global.anthropic.claude-opus-4-7": ["bedrock"],
  "global.anthropic.claude-sonnet-4-20250514-v1:0": ["bedrock"],
  "global.anthropic.claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "global.anthropic.claude-sonnet-4-6": ["bedrock"],
  "google.gemma-3-12b-it": ["bedrock"],
  "google.gemma-3-27b-it": ["bedrock"],
  "google.gemma-3-4b-it": ["bedrock"],
  "jp.anthropic.claude-haiku-4-5-20251001-v1:0": ["bedrock"],
  "jp.anthropic.claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "meta.llama4-maverick-17b-instruct-v1:0": ["bedrock"],
  "meta.llama4-scout-17b-instruct-v1:0": ["bedrock"],
  "minimax.minimax-m2": ["bedrock"],
  "minimax.minimax-m2.1": ["bedrock"],
  "minimax.minimax-m2.5": ["bedrock"],
  "mistral.devstral-2-123b": ["bedrock"],
  "mistral.magistral-small-2509": ["bedrock"],
  "mistral.ministral-3-14b-instruct": ["bedrock"],
  "mistral.ministral-3-3b-instruct": ["bedrock"],
  "mistral.ministral-3-8b-instruct": ["bedrock"],
  "mistral.mistral-large-3-675b-instruct": ["bedrock"],
  "mistral.voxtral-mini-3b-2507": ["bedrock"],
  "mistral.voxtral-small-24b-2507": ["bedrock"],
  "moonshot.kimi-k2-thinking": ["bedrock"],
  "moonshotai.kimi-k2.5": ["bedrock"],
  "nvidia.nemotron-nano-12b-v2": ["bedrock"],
  "nvidia.nemotron-nano-3-30b": ["bedrock"],
  "nvidia.nemotron-nano-9b-v2": ["bedrock"],
  "nvidia.nemotron-super-3-120b": ["bedrock"],
  "openai.gpt-oss-120b-1:0": ["bedrock"],
  "openai.gpt-oss-20b-1:0": ["bedrock"],
  "openai.gpt-oss-safeguard-120b": ["bedrock"],
  "openai.gpt-oss-safeguard-20b": ["bedrock"],
  "qwen.qwen3-235b-a22b-2507-v1:0": ["bedrock"],
  "qwen.qwen3-32b-v1:0": ["bedrock"],
  "qwen.qwen3-coder-30b-a3b-v1:0": ["bedrock"],
  "qwen.qwen3-coder-480b-a35b-v1:0": ["bedrock"],
  "qwen.qwen3-coder-next": ["bedrock"],
  "qwen.qwen3-next-80b-a3b": ["bedrock"],
  "qwen.qwen3-vl-235b-a22b": ["bedrock"],
  "us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0": ["bedrock"],
  "us.amazon.nova-2-lite-v1:0": ["bedrock"],
  "us.amazon.nova-2-pro-preview-20251202-v1:0": ["bedrock"],
  "us.amazon.nova-premier-v1:0": ["bedrock"],
  "us.anthropic.claude-opus-4-6-v1": ["bedrock"],
  "us.anthropic.claude-opus-4-7": ["bedrock"],
  "us.deepseek.r1-v1:0": ["bedrock"],
  "us.deepseek.v3.2": ["bedrock"],
  "us.meta.llama4-maverick-17b-instruct-v1:0": ["bedrock"],
  "us.meta.llama4-scout-17b-instruct-v1:0": ["bedrock"],
  "us.mistral.pixtral-large-2502-v1:0": ["bedrock"],
  "us.writer.palmyra-x4-v1:0": ["bedrock"],
  "us.writer.palmyra-x5-v1:0": ["bedrock"],
  "writer.palmyra-x4-v1:0": ["bedrock"],
  "writer.palmyra-x5-v1:0": ["bedrock"],
  "zai.glm-4.7": ["bedrock"],
  "zai.glm-4.7-flash": ["bedrock"],
  "zai.glm-5": ["bedrock"],
  "bedrock_mantle/openai.gpt-oss-120b": ["bedrock"],
  "bedrock_mantle/openai.gpt-oss-20b": ["bedrock"],
  "bedrock_mantle/openai.gpt-oss-safeguard-120b": ["bedrock"],
  "bedrock_mantle/openai.gpt-oss-safeguard-20b": ["bedrock"],
  "llama-3.3-70b": ["cerebras"],
  "llama3.1-70b": ["cerebras"],
  "qwen-3-32b": ["cerebras"],
  "zai-glm-4.6": ["cerebras"],
  "zai-glm-4.7": ["cerebras"],
  "databricks-bge-large-en": ["databricks"],
  "databricks-claude-haiku-4-5": ["databricks"],
  "databricks-claude-opus-4": ["databricks"],
  "databricks-claude-opus-4-1": ["databricks"],
  "databricks-claude-opus-4-5": ["databricks"],
  "databricks-claude-sonnet-4": ["databricks"],
  "databricks-claude-sonnet-4-1": ["databricks"],
  "databricks-claude-sonnet-4-5": ["databricks"],
  "databricks-gemini-2-5-flash": ["databricks"],
  "databricks-gemini-2-5-pro": ["databricks"],
  "databricks-gemma-3-12b": ["databricks"],
  "databricks-gpt-5": ["databricks"],
  "databricks-gpt-5-1": ["databricks"],
  "databricks-gpt-5-mini": ["databricks"],
  "databricks-gpt-5-nano": ["databricks"],
  "databricks-gpt-oss-120b": ["databricks"],
  "databricks-gpt-oss-20b": ["databricks"],
  "databricks-gte-large-en": ["databricks"],
  "databricks-llama-2-70b-chat": ["databricks"],
  "databricks-llama-4-maverick": ["databricks"],
  "databricks-meta-llama-3-70b-instruct": ["databricks"],
  "databricks-mixtral-8x7b-instruct": ["databricks"],
  "databricks-mpt-30b-instruct": ["databricks"],
  "databricks-mpt-7b-instruct": ["databricks"],
  "fireworks_ai/accounts/fireworks/models/": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/chronos-hermes-13b-v2": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-13b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-13b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/code-llama-13b-python": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-34b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-34b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/code-llama-34b-python": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-70b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-70b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/code-llama-70b-python": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-llama-7b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/code-llama-7b-python": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/code-qwen-1p5-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/codegemma-2b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/codegemma-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/cogito-671b-v2-p1": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/cogito-v1-preview-llama-3b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/cogito-v1-preview-llama-70b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/cogito-v1-preview-llama-8b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/cogito-v1-preview-qwen-14b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/cogito-v1-preview-qwen-32b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/dbrx-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-1b-base": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-33b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-7b-base": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-7b-base-v1p5": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-7b-instruct-v1p5": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-v2-lite-base": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-v2-lite-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-prover-v2": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-0528-distill-qwen3-8b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-distill-llama-70b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-distill-llama-8b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-distill-qwen-14b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-distill-qwen-1p5b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-distill-qwen-32b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-distill-qwen-7b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-v2-lite-chat": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-v2p5": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-v3p1-terminus": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-v3p2": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/devstral-small-2505": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/dobby-mini-unhinged-plus-llama-3-1-8b":
    ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/dobby-unhinged-llama-3-3-70b-new": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/dolphin-2-9-2-qwen2-72b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/dolphin-2p6-mixtral-8x7b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/ernie-4p5-21b-a3b-pt": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/ernie-4p5-300b-a47b-pt": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/fare-20b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/firefunction-v1": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/firellava-13b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/firesearch-ocr-v6": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/fireworks-asr-large": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/fireworks-asr-v2": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/flux-1-dev": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/flux-1-dev-controlnet-union": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/flux-1-dev-fp8": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/flux-1-schnell": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/flux-1-schnell-fp8": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/flux-kontext-max": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/flux-kontext-pro": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gemma-2b-it": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gemma-3-27b-it": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gemma-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gemma-7b-it": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gemma2-9b-it": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/glm-4p5v": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/glm-4p6": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gpt-oss-safeguard-120b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/gpt-oss-safeguard-20b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/hermes-2-pro-mistral-7b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/internvl3-38b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/internvl3-78b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/internvl3-8b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/japanese-stable-diffusion-xl": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/kat-coder": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/kat-dev-32b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/kat-dev-72b-exp": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/kimi-k2-instruct-0905": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/kimi-k2-thinking": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/kimi-k2p5": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-guard-2-8b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-guard-3-1b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-guard-3-8b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v2-13b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v2-13b-chat": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v2-70b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v2-70b-chat": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v2-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v2-7b-chat": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v3-70b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v3-70b-instruct-hf": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3-8b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v3-8b-instruct-hf": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p1-405b-instruct-long": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p1-70b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p1-70b-instruct-1b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p1-nemotron-70b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p2-1b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v3p2-3b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v3p3-70b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llamaguard-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llava-yi-34b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/minimax-m1-80k": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/minimax-m2": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/minimax-m2p1": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/ministral-3-14b-instruct-2512": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/ministral-3-3b-instruct-2512": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/ministral-3-8b-instruct-2512": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mistral-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/mistral-7b-instruct-4k": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mistral-7b-instruct-v0p2": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mistral-7b-instruct-v3": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mistral-7b-v0p2": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/mistral-large-3-fp8": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/mistral-nemo-base-2407": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mistral-nemo-instruct-2407": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mistral-small-24b-instruct-2501": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mixtral-8x22b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/mixtral-8x22b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mixtral-8x7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/mixtral-8x7b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/mixtral-8x7b-instruct-hf": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mythomax-l2-13b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/nemotron-nano-v2-12b-vl": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/nous-capybara-7b-v1p9": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/nous-hermes-2-mixtral-8x7b-dpo": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/nous-hermes-2-yi-34b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/nous-hermes-llama2-13b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/nous-hermes-llama2-70b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/nous-hermes-llama2-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/nvidia-nemotron-nano-12b-v2": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/nvidia-nemotron-nano-9b-v2": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/openchat-3p5-0106-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/openhermes-2-mistral-7b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/openhermes-2p5-mistral-7b": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/openorca-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/phi-2-3b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/phi-3-mini-128k-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/phi-3-vision-128k-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/phind-code-llama-34b-python-v1": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/phind-code-llama-34b-v1": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/phind-code-llama-34b-v2": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/playground-v2-1024px-aesthetic": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/playground-v2-5-1024px-aesthetic": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/pythia-12b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen-qwq-32b-preview": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen-v2p5-14b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen-v2p5-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen1p5-72b-chat": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2-7b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2-vl-2b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2-vl-72b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2-vl-7b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-0p5b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-14b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-1p5b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-32b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-32b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-72b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-72b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-7b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-0p5b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-0p5b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-14b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-14b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-1p5b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-1p5b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-32b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-32b-instruct-128k": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-32b-instruct-32k-rope":
    ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-32b-instruct-64k": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-3b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-3b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-7b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-math-72b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-vl-32b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-vl-3b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-vl-72b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-vl-7b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-0p6b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-14b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-1p7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-1p7b-fp8-draft": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-1p7b-fp8-draft-131072": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-1p7b-fp8-draft-40960": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-235b-a22b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-235b-a22b-instruct-2507": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-235b-a22b-thinking-2507": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-30b-a3b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-30b-a3b-instruct-2507": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-30b-a3b-thinking-2507": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-32b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-4b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-4b-instruct-2507": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-8b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-coder-30b-a3b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-coder-480b-a35b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-coder-480b-instruct-bf16": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-embedding-0p6b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-embedding-4b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-next-80b-a3b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-next-80b-a3b-thinking": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-reranker-0p6b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-reranker-4b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-reranker-8b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-vl-235b-a22b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-vl-235b-a22b-thinking": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-vl-30b-a3b-thinking": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen3-vl-32b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-vl-8b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwq-32b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/rolm-ocr": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/snorkel-mistral-7b-pairrm-dpo": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/SSD-1B": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/stable-diffusion-xl-1024-v1-0": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/stablecode-3b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/starcoder-16b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/starcoder-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/starcoder2-15b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/starcoder2-3b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/starcoder2-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/toppy-m-7b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/whisper-v3": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/whisper-v3-turbo": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/yi-34b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/yi-34b-200k-capybara": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/yi-34b-chat": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/yi-6b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/zephyr-7b-beta": ["fireworks"],
  "fireworks_ai/glm-4p7": ["fireworks"],
  "fireworks_ai/kimi-k2p5": ["fireworks"],
  "fireworks_ai/minimax-m2p1": ["fireworks"],
  "gemini-2.0-flash-exp-image-generation": ["google"],
  "gemini-2.5-flash-native-audio-latest": ["google"],
  "gemini-2.5-flash-native-audio-preview-09-2025": ["google"],
  "gemini-2.5-flash-native-audio-preview-12-2025": ["google"],
  "gemini-2.5-flash-preview-tts": ["google"],
  "gemini-3.1-flash-live-preview": ["google"],
  "gemini-flash-latest": ["google"],
  "gemini-flash-lite-latest": ["google"],
  "gemini-pro-latest": ["google"],
  "deep-research-pro-preview-12-2025": ["google", "vertex"],
  "gemini-2.5-computer-use-preview-10-2025": ["google", "vertex"],
  "gemini-2.5-flash-image": ["google", "vertex"],
  "gemini-2.5-pro-preview-tts": ["google", "vertex"],
  "gemini-3.1-flash-image-preview": ["google", "vertex"],
  "gemini-embedding-001": ["google", "vertex"],
  "gemini-embedding-2-preview": ["google", "vertex"],
  "gemini-exp-1114": ["google"],
  "gemini-gemma-2-27b-it": ["google"],
  "gemini-gemma-2-9b-it": ["google"],
  "gemini-live-2.5-flash-preview-native-audio-09-2025": ["google", "vertex"],
  "gemini-robotics-er-1.5-preview": ["google", "vertex"],
  "gemma-3-27b-it": ["google"],
  "imagen-3.0-fast-generate-001": ["google"],
  "imagen-3.0-generate-001": ["google"],
  "imagen-3.0-generate-002": ["google"],
  "imagen-4.0-fast-generate-001": ["google"],
  "imagen-4.0-generate-001": ["google"],
  "imagen-4.0-ultra-generate-001": ["google"],
  "lyria-3-clip-preview": ["google"],
  "lyria-3-pro-preview": ["google"],
  "veo-2.0-generate-001": ["google"],
  "veo-3.1-fast-generate-001": ["google"],
  "veo-3.1-fast-generate-preview": ["google"],
  "veo-3.1-generate-001": ["google"],
  "veo-3.1-generate-preview": ["google"],
  "veo-3.1-lite-generate-preview": ["google"],
  "google_pse/search": ["google"],
  "meta-llama/llama-guard-4-12b": ["groq"],
  "openai/gpt-oss-safeguard-20b": ["groq"],
  "playai-tts": ["groq"],
  "whisper-large-v3": ["groq"],
  "whisper-large-v3-turbo": ["groq"],
  "codestral-2405": ["mistral"],
  "codestral-2508": ["mistral"],
  "codestral-embed": ["mistral"],
  "codestral-embed-2505": ["mistral"],
  "codestral-mamba-latest": ["mistral"],
  "devstral-2512": ["mistral"],
  "devstral-latest": ["mistral"],
  "devstral-medium-2507": ["mistral"],
  "devstral-medium-latest": ["mistral"],
  "devstral-small-2505": ["mistral"],
  "labs-devstral-small-2512": ["mistral"],
  "magistral-medium-1-2-2509": ["mistral"],
  "magistral-medium-2509": ["mistral"],
  "magistral-small-1-2-2509": ["mistral"],
  "ministral-3-14b-2512": ["mistral"],
  "ministral-3-3b-2512": ["mistral"],
  "ministral-3-8b-2512": ["mistral"],
  "mistral-embed": ["mistral"],
  "mistral-large-2402": ["mistral"],
  "mistral-large-2407": ["mistral"],
  "mistral-large-2512": ["mistral"],
  "mistral-large-3": ["mistral"],
  "mistral-medium-2312": ["mistral"],
  "mistral-medium-3-1-2508": ["mistral"],
  "mistral-ocr-2505-completion": ["mistral"],
  "mistral-ocr-latest": ["mistral"],
  "mistral-small-3-2-2506": ["mistral"],
  "open-mistral-7b": ["mistral"],
  "open-mixtral-8x7b": ["mistral"],
  "1024-x-1024/dall-e-2": ["openai", "azure"],
  "1024-x-1024/gpt-image-1.5": ["openai", "azure"],
  "1024-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "1024-x-1536/gpt-image-1.5": ["openai", "azure"],
  "1024-x-1536/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "1536-x-1024/gpt-image-1.5": ["openai", "azure"],
  "1536-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "256-x-256/dall-e-2": ["openai", "azure"],
  "512-x-512/dall-e-2": ["openai", "azure"],
  "chatgpt-image-latest": ["openai", "azure"],
  "codex-mini-latest": ["openai", "azure"],
  "dall-e-2": ["openai", "azure"],
  "dall-e-3": ["openai", "azure"],
  "ft:gpt-3.5-turbo": ["openai", "azure"],
  "ft:gpt-3.5-turbo-0125": ["openai", "azure"],
  "ft:gpt-3.5-turbo-0613": ["openai", "azure"],
  "ft:gpt-3.5-turbo-1106": ["openai", "azure"],
  "ft:gpt-4-0613": ["openai", "azure"],
  "ft:gpt-4.1-2025-04-14": ["openai", "azure"],
  "ft:gpt-4.1-mini-2025-04-14": ["openai", "azure"],
  "ft:gpt-4.1-nano-2025-04-14": ["openai", "azure"],
  "ft:gpt-4o-2024-08-06": ["openai", "azure"],
  "ft:gpt-4o-2024-11-20": ["openai", "azure"],
  "ft:gpt-4o-mini-2024-07-18": ["openai", "azure"],
  "ft:o4-mini-2025-04-16": ["openai", "azure"],
  "gpt-4o-audio-preview": ["openai", "azure"],
  "gpt-4o-audio-preview-2024-12-17": ["openai", "azure"],
  "gpt-4o-audio-preview-2025-06-03": ["openai", "azure"],
  "gpt-4o-mini-audio-preview": ["openai", "azure"],
  "gpt-4o-mini-audio-preview-2024-12-17": ["openai", "azure"],
  "gpt-4o-mini-realtime-preview": ["openai", "azure"],
  "gpt-4o-mini-realtime-preview-2024-12-17": ["openai", "azure"],
  "gpt-4o-mini-transcribe": ["openai", "azure"],
  "gpt-4o-mini-transcribe-2025-03-20": ["openai", "azure"],
  "gpt-4o-mini-transcribe-2025-12-15": ["openai", "azure"],
  "gpt-4o-mini-tts": ["openai", "azure"],
  "gpt-4o-mini-tts-2025-03-20": ["openai", "azure"],
  "gpt-4o-mini-tts-2025-12-15": ["openai", "azure"],
  "gpt-4o-realtime-preview": ["openai", "azure"],
  "gpt-4o-realtime-preview-2024-12-17": ["openai", "azure"],
  "gpt-4o-realtime-preview-2025-06-03": ["openai", "azure"],
  "gpt-4o-transcribe": ["openai", "azure"],
  "gpt-4o-transcribe-diarize": ["openai", "azure"],
  "gpt-5-search-api": ["openai", "azure"],
  "gpt-5-search-api-2025-10-14": ["openai", "azure"],
  "gpt-5.1-codex-max": ["openai", "azure"],
  "gpt-5.2-pro": ["openai", "azure"],
  "gpt-5.2-pro-2025-12-11": ["openai", "azure"],
  "gpt-5.4-pro-2026-03-05": ["openai", "azure"],
  "gpt-audio": ["openai", "azure"],
  "gpt-audio-1.5": ["openai", "azure"],
  "gpt-audio-2025-08-28": ["openai", "azure"],
  "gpt-audio-mini": ["openai", "azure"],
  "gpt-audio-mini-2025-10-06": ["openai", "azure"],
  "gpt-audio-mini-2025-12-15": ["openai", "azure"],
  "gpt-image-1": ["openai", "azure"],
  "gpt-image-1-mini": ["openai", "azure"],
  "gpt-image-1.5": ["openai", "azure"],
  "gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "gpt-realtime": ["openai", "azure"],
  "gpt-realtime-1.5": ["openai", "azure"],
  "gpt-realtime-2025-08-28": ["openai", "azure"],
  "gpt-realtime-mini": ["openai", "azure"],
  "gpt-realtime-mini-2025-10-06": ["openai", "azure"],
  "gpt-realtime-mini-2025-12-15": ["openai", "azure"],
  "hd/1024-x-1024/dall-e-3": ["openai", "azure"],
  "hd/1024-x-1792/dall-e-3": ["openai", "azure"],
  "hd/1792-x-1024/dall-e-3": ["openai", "azure"],
  "high/1024-x-1024/gpt-image-1": ["openai", "azure"],
  "high/1024-x-1024/gpt-image-1.5": ["openai", "azure"],
  "high/1024-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "high/1024-x-1536/gpt-image-1": ["openai", "azure"],
  "high/1024-x-1536/gpt-image-1.5": ["openai", "azure"],
  "high/1024-x-1536/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "high/1536-x-1024/gpt-image-1": ["openai", "azure"],
  "high/1536-x-1024/gpt-image-1.5": ["openai", "azure"],
  "high/1536-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "low/1024-x-1024/gpt-image-1": ["openai", "azure"],
  "low/1024-x-1024/gpt-image-1-mini": ["openai", "azure"],
  "low/1024-x-1024/gpt-image-1.5": ["openai", "azure"],
  "low/1024-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "low/1024-x-1536/gpt-image-1": ["openai", "azure"],
  "low/1024-x-1536/gpt-image-1-mini": ["openai", "azure"],
  "low/1024-x-1536/gpt-image-1.5": ["openai", "azure"],
  "low/1024-x-1536/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "low/1536-x-1024/gpt-image-1": ["openai", "azure"],
  "low/1536-x-1024/gpt-image-1-mini": ["openai", "azure"],
  "low/1536-x-1024/gpt-image-1.5": ["openai", "azure"],
  "low/1536-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "medium/1024-x-1024/gpt-image-1": ["openai", "azure"],
  "medium/1024-x-1024/gpt-image-1-mini": ["openai", "azure"],
  "medium/1024-x-1024/gpt-image-1.5": ["openai", "azure"],
  "medium/1024-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "medium/1024-x-1536/gpt-image-1": ["openai", "azure"],
  "medium/1024-x-1536/gpt-image-1-mini": ["openai", "azure"],
  "medium/1024-x-1536/gpt-image-1.5": ["openai", "azure"],
  "medium/1024-x-1536/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "medium/1536-x-1024/gpt-image-1": ["openai", "azure"],
  "medium/1536-x-1024/gpt-image-1-mini": ["openai", "azure"],
  "medium/1536-x-1024/gpt-image-1.5": ["openai", "azure"],
  "medium/1536-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "o3-deep-research": ["openai", "azure"],
  "o3-deep-research-2025-06-26": ["openai", "azure"],
  "o4-mini-deep-research": ["openai", "azure"],
  "o4-mini-deep-research-2025-06-26": ["openai", "azure"],
  "omni-moderation-2024-09-26": ["openai", "azure"],
  "omni-moderation-latest": ["openai", "azure"],
  "openai/container": ["openai", "azure"],
  "openai/sora-2": ["openai", "azure"],
  "openai/sora-2-pro": ["openai", "azure"],
  "openai/sora-2-pro-high-res": ["openai", "azure"],
  "sora-2": ["openai", "azure"],
  "sora-2-pro": ["openai", "azure"],
  "sora-2-pro-high-res": ["openai", "azure"],
  "standard/1024-x-1024/dall-e-3": ["openai", "azure"],
  "standard/1024-x-1024/gpt-image-1.5": ["openai", "azure"],
  "standard/1024-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "standard/1024-x-1536/gpt-image-1.5": ["openai", "azure"],
  "standard/1024-x-1536/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "standard/1024-x-1792/dall-e-3": ["openai", "azure"],
  "standard/1536-x-1024/gpt-image-1.5": ["openai", "azure"],
  "standard/1536-x-1024/gpt-image-1.5-2025-12-16": ["openai", "azure"],
  "standard/1792-x-1024/dall-e-3": ["openai", "azure"],
  "text-embedding-3-large": ["openai", "azure"],
  "text-embedding-3-small": ["openai", "azure"],
  "text-embedding-ada-002": ["openai", "azure"],
  "text-embedding-ada-002-v2": ["openai", "azure"],
  "text-moderation-007": ["openai", "azure"],
  "text-moderation-latest": ["openai", "azure"],
  "text-moderation-stable": ["openai", "azure"],
  "tts-1": ["openai", "azure"],
  "tts-1-1106": ["openai", "azure"],
  "tts-1-hd": ["openai", "azure"],
  "tts-1-hd-1106": ["openai", "azure"],
  "whisper-1": ["openai", "azure"],
  "anthropic/claude-haiku-4-5": ["perplexity"],
  "anthropic/claude-opus-4-5": ["perplexity"],
  "anthropic/claude-opus-4-6": ["perplexity"],
  "anthropic/claude-opus-4-7": ["perplexity"],
  "anthropic/claude-sonnet-4-5": ["perplexity"],
  "codellama-34b-instruct": ["perplexity"],
  "codellama-70b-instruct": ["perplexity"],
  "google/gemini-2.5-flash": ["perplexity"],
  "google/gemini-2.5-pro": ["perplexity"],
  "google/gemini-3-flash-preview": ["perplexity"],
  "google/gemini-3-pro-preview": ["perplexity"],
  "llama-2-70b-chat": ["perplexity"],
  "llama-3.1-70b-instruct": ["perplexity"],
  "llama-3.1-8b-instruct": ["perplexity"],
  "mistral-7b-instruct": ["perplexity"],
  "mixtral-8x7b-instruct": ["perplexity"],
  "openai/gpt-5-mini": ["perplexity"],
  "openai/gpt-5.1": ["perplexity"],
  "openai/gpt-5.2": ["perplexity"],
  "perplexity/sonar": ["perplexity"],
  "pplx-70b-chat": ["perplexity"],
  "pplx-70b-online": ["perplexity"],
  "pplx-7b-chat": ["perplexity"],
  "pplx-7b-online": ["perplexity"],
  "pplx-embed-v1-0.6b": ["perplexity"],
  "pplx-embed-v1-4b": ["perplexity"],
  "preset/advanced-deep-research": ["perplexity"],
  "preset/deep-research": ["perplexity"],
  "preset/fast-search": ["perplexity"],
  "preset/pro-search": ["perplexity"],
  search: ["perplexity"],
  "sonar-deep-research": ["perplexity"],
  "sonar-medium-chat": ["perplexity"],
  "sonar-medium-online": ["perplexity"],
  "sonar-small-chat": ["perplexity"],
  "sonar-small-online": ["perplexity"],
  "xai/grok-4-1-fast-non-reasoning": ["perplexity"],
  "replicate/anthropic/claude-3.5-haiku": ["replicate"],
  "replicate/anthropic/claude-3.5-sonnet": ["replicate"],
  "replicate/anthropic/claude-3.7-sonnet": ["replicate"],
  "replicate/anthropic/claude-4-sonnet": ["replicate"],
  "replicate/anthropic/claude-4.5-haiku": ["replicate"],
  "replicate/anthropic/claude-4.5-sonnet": ["replicate"],
  "replicate/deepseek-ai/deepseek-r1": ["replicate"],
  "replicate/deepseek-ai/deepseek-v3": ["replicate"],
  "replicate/deepseek-ai/deepseek-v3.1": ["replicate"],
  "replicate/google/gemini-2.5-flash": ["replicate"],
  "replicate/google/gemini-3-pro": ["replicate"],
  "replicate/ibm-granite/granite-3.3-8b-instruct": ["replicate"],
  "replicate/meta/llama-2-13b": ["replicate"],
  "replicate/meta/llama-2-13b-chat": ["replicate"],
  "replicate/meta/llama-2-70b": ["replicate"],
  "replicate/meta/llama-2-70b-chat": ["replicate"],
  "replicate/meta/llama-2-7b": ["replicate"],
  "replicate/meta/llama-2-7b-chat": ["replicate"],
  "replicate/meta/llama-3-70b": ["replicate"],
  "replicate/meta/llama-3-70b-instruct": ["replicate"],
  "replicate/meta/llama-3-8b": ["replicate"],
  "replicate/meta/llama-3-8b-instruct": ["replicate"],
  "replicate/mistralai/mistral-7b-instruct-v0.2": ["replicate"],
  "replicate/mistralai/mistral-7b-v0.1": ["replicate"],
  "replicate/mistralai/mixtral-8x7b-instruct-v0.1": ["replicate"],
  "replicate/openai/gpt-4.1": ["replicate"],
  "replicate/openai/gpt-4.1-mini": ["replicate"],
  "replicate/openai/gpt-4.1-nano": ["replicate"],
  "replicate/openai/gpt-4o": ["replicate"],
  "replicate/openai/gpt-4o-mini": ["replicate"],
  "replicate/openai/gpt-5": ["replicate"],
  "replicate/openai/gpt-5-mini": ["replicate"],
  "replicate/openai/gpt-5-nano": ["replicate"],
  "replicate/openai/gpt-oss-120b": ["replicate"],
  "replicate/openai/o1": ["replicate"],
  "replicate/openai/o1-mini": ["replicate"],
  "replicate/openai/o4-mini": ["replicate"],
  "replicate/qwen/qwen3-235b-a22b-instruct-2507": ["replicate"],
  "replicate/xai/grok-4": ["replicate"],
  "replicateopenai/gpt-oss-20b": ["replicate"],
  "babbage-002": ["openai", "azure"],
  "davinci-002": ["openai", "azure"],
  "ft:babbage-002": ["openai", "azure"],
  "ft:davinci-002": ["openai", "azure"],
  "baai/bge-base-en-v1.5": ["together"],
  "BAAI/bge-base-en-v1.5": ["together"],
  "deepseek-ai/DeepSeek-R1-0528-tput": ["together"],
  "deepseek-ai/DeepSeek-V3.1": ["together"],
  "moonshotai/Kimi-K2-Instruct-0905": ["together"],
  "moonshotai/Kimi-K2.5": ["together"],
  "Qwen/Qwen3-235B-A22B-fp8-tput": ["together"],
  "Qwen/Qwen3-235B-A22B-Instruct-2507-tput": ["together"],
  "Qwen/Qwen3-235B-A22B-Thinking-2507": ["together"],
  "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8": ["together"],
  "Qwen/Qwen3-Next-80B-A3B-Instruct": ["together"],
  "Qwen/Qwen3-Next-80B-A3B-Thinking": ["together"],
  "Qwen/Qwen3.5-397B-A17B": ["together"],
  "togethercomputer/CodeLlama-34b-Instruct": ["together"],
  "zai-org/GLM-4.5-Air-FP8": ["together"],
  "zai-org/GLM-4.6": ["together"],
  "zai-org/GLM-4.7": ["together"],
  "together-ai-21.1b-41b": ["together"],
  "together-ai-4.1b-8b": ["together"],
  "together-ai-41.1b-80b": ["together"],
  "together-ai-8.1b-21b": ["together"],
  "together-ai-81.1b-110b": ["together"],
  "together-ai-embedding-151m-to-350m": ["together"],
  "together-ai-embedding-up-to-150m": ["together"],
  "together-ai-up-to-4b": ["together"],
  "vertex_ai/chirp": ["vertex"],
  "vertex_ai/deepseek-ai/deepseek-ocr-maas": ["vertex"],
  "vertex_ai/gemini-3-flash-preview": ["vertex"],
  "vertex_ai/gemini-3-pro-preview": ["vertex"],
  "vertex_ai/gemini-3.1-pro-preview": ["vertex"],
  "vertex_ai/gemini-3.1-pro-preview-customtools": ["vertex"],
  "vertex_ai/gemini-embedding-2-preview": ["vertex"],
  "vertex_ai/mistral-ocr-2505": ["vertex"],
  "vertex_ai/search_api": ["vertex"],
  "vertex_ai/jamba-1.5": ["vertex"],
  "vertex_ai/jamba-1.5-large": ["vertex"],
  "vertex_ai/jamba-1.5-large@001": ["vertex"],
  "vertex_ai/jamba-1.5-mini": ["vertex"],
  "vertex_ai/jamba-1.5-mini@001": ["vertex"],
  "vertex_ai/claude-3-5-haiku": ["anthropic"],
  "vertex_ai/claude-3-5-haiku@20241022": ["anthropic"],
  "vertex_ai/claude-3-5-sonnet": ["anthropic"],
  "vertex_ai/claude-3-5-sonnet@20240620": ["anthropic"],
  "vertex_ai/claude-3-7-sonnet@20250219": ["anthropic"],
  "vertex_ai/claude-3-haiku": ["anthropic"],
  "vertex_ai/claude-3-haiku@20240307": ["anthropic"],
  "vertex_ai/claude-3-opus": ["anthropic"],
  "vertex_ai/claude-3-opus@20240229": ["anthropic"],
  "vertex_ai/claude-3-sonnet": ["anthropic"],
  "vertex_ai/claude-3-sonnet@20240229": ["anthropic"],
  "vertex_ai/claude-haiku-4-5": ["anthropic"],
  "vertex_ai/claude-haiku-4-5@20251001": ["anthropic"],
  "vertex_ai/claude-opus-4": ["anthropic"],
  "vertex_ai/claude-opus-4-1": ["anthropic"],
  "vertex_ai/claude-opus-4-1@20250805": ["anthropic"],
  "vertex_ai/claude-opus-4-5": ["anthropic"],
  "vertex_ai/claude-opus-4-5@20251101": ["anthropic"],
  "vertex_ai/claude-opus-4-6": ["anthropic"],
  "vertex_ai/claude-opus-4-6@default": ["anthropic"],
  "vertex_ai/claude-opus-4-7": ["anthropic"],
  "vertex_ai/claude-opus-4-7@default": ["anthropic"],
  "vertex_ai/claude-opus-4@20250514": ["anthropic"],
  "vertex_ai/claude-sonnet-4": ["anthropic"],
  "vertex_ai/claude-sonnet-4-5": ["anthropic"],
  "vertex_ai/claude-sonnet-4-5@20250929": ["anthropic"],
  "vertex_ai/claude-sonnet-4-6": ["anthropic"],
  "vertex_ai/claude-sonnet-4-6@default": ["anthropic"],
  "vertex_ai/claude-sonnet-4@20250514": ["anthropic"],
  "vertex_ai/deepseek-ai/deepseek-r1-0528-maas": ["vertex"],
  "vertex_ai/deepseek-ai/deepseek-v3.1-maas": ["vertex"],
  "vertex_ai/deepseek-ai/deepseek-v3.2-maas": ["vertex"],
  multimodalembedding: ["vertex"],
  "multimodalembedding@001": ["vertex"],
  "text-embedding-004": ["vertex"],
  "text-embedding-005": ["vertex"],
  "text-embedding-large-exp-03-07": ["vertex"],
  "text-embedding-preview-0409": ["vertex"],
  "text-multilingual-embedding-002": ["vertex"],
  "vertex_ai/imagegeneration@006": ["vertex"],
  "vertex_ai/imagen-3.0-capability-001": ["vertex"],
  "vertex_ai/imagen-3.0-fast-generate-001": ["vertex"],
  "vertex_ai/imagen-3.0-generate-001": ["vertex"],
  "vertex_ai/imagen-3.0-generate-002": ["vertex"],
  "vertex_ai/imagen-4.0-fast-generate-001": ["vertex"],
  "vertex_ai/imagen-4.0-generate-001": ["vertex"],
  "vertex_ai/imagen-4.0-ultra-generate-001": ["vertex"],
  "gemini-flash-experimental": ["vertex"],
  "medlm-large": ["vertex"],
  "medlm-medium": ["vertex"],
  "vertex_ai/deep-research-pro-preview-12-2025": ["vertex"],
  "vertex_ai/gemini-2.5-flash-image": ["vertex"],
  "vertex_ai/gemini-3-pro-image-preview": ["vertex"],
  "vertex_ai/gemini-3.1-flash-image-preview": ["vertex"],
  "vertex_ai/gemini-3.1-flash-lite-preview": ["vertex"],
  "vertex_ai/meta/llama-3.1-405b-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama-3.1-70b-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama-3.1-8b-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama-3.2-90b-vision-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama-4-maverick-17b-128e-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama-4-maverick-17b-16e-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama-4-scout-17b-128e-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama-4-scout-17b-16e-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama3-405b-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama3-70b-instruct-maas": ["vertex"],
  "vertex_ai/meta/llama3-8b-instruct-maas": ["vertex"],
  "vertex_ai/minimaxai/minimax-m2-maas": ["vertex"],
  "vertex_ai/codestral-2": ["mistral"],
  "vertex_ai/codestral-2@001": ["mistral"],
  "vertex_ai/codestral-2501": ["mistral"],
  "vertex_ai/codestral@2405": ["mistral"],
  "vertex_ai/codestral@latest": ["mistral"],
  "vertex_ai/mistral-large-2411": ["mistral"],
  "vertex_ai/mistral-large@2407": ["mistral"],
  "vertex_ai/mistral-large@2411-001": ["mistral"],
  "vertex_ai/mistral-large@latest": ["mistral"],
  "vertex_ai/mistral-medium-3": ["mistral"],
  "vertex_ai/mistral-medium-3@001": ["mistral"],
  "vertex_ai/mistral-nemo@2407": ["mistral"],
  "vertex_ai/mistral-nemo@latest": ["mistral"],
  "vertex_ai/mistral-small-2503": ["mistral"],
  "vertex_ai/mistral-small-2503@001": ["mistral"],
  "vertex_ai/mistralai/codestral-2": ["mistral"],
  "vertex_ai/mistralai/codestral-2@001": ["mistral"],
  "vertex_ai/mistralai/mistral-medium-3": ["mistral"],
  "vertex_ai/mistralai/mistral-medium-3@001": ["mistral"],
  "vertex_ai/moonshotai/kimi-k2-thinking-maas": ["vertex"],
  "vertex_ai/openai/gpt-oss-120b-maas": ["openai", "azure"],
  "vertex_ai/openai/gpt-oss-20b-maas": ["openai", "azure"],
  "vertex_ai/qwen/qwen3-235b-a22b-instruct-2507-maas": ["vertex"],
  "vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas": ["vertex"],
  "vertex_ai/qwen/qwen3-next-80b-a3b-instruct-maas": ["vertex"],
  "vertex_ai/qwen/qwen3-next-80b-a3b-thinking-maas": ["vertex"],
  "text-unicorn": ["vertex"],
  "text-unicorn@001": ["vertex"],
  "vertex_ai/veo-2.0-generate-001": ["vertex"],
  "vertex_ai/veo-3.0-fast-generate-001": ["vertex"],
  "vertex_ai/veo-3.0-generate-001": ["vertex"],
  "vertex_ai/veo-3.1-fast-generate-001": ["vertex"],
  "vertex_ai/veo-3.1-fast-generate-preview": ["vertex"],
  "vertex_ai/veo-3.1-generate-001": ["vertex"],
  "vertex_ai/veo-3.1-generate-preview": ["vertex"],
  "vertex_ai/zai-org/glm-4.7-maas": ["vertex"],
  "vertex_ai/zai-org/glm-5-maas": ["vertex"],
  "grok-4.20-0309-reasoning": ["xAI"],
  "grok-4.20-beta-0309-non-reasoning": ["xAI"],
  "grok-4.20-beta-0309-reasoning": ["xAI"],
  "grok-4.20-multi-agent-beta-0309": ["xAI"],
  "fireworks-ai-4.1b-to-16b": ["fireworks"],
  "fireworks-ai-56b-to-176b": ["fireworks"],
  "fireworks-ai-above-16b": ["fireworks"],
  "fireworks-ai-default": ["fireworks"],
  "fireworks-ai-embedding-150m-to-350m": ["fireworks"],
  "fireworks-ai-embedding-up-to-150m": ["fireworks"],
  "fireworks-ai-moe-up-to-56b": ["fireworks"],
  "fireworks-ai-up-to-4b": ["fireworks"],
  "fireworks_ai/WhereIsAI/UAE-Large-V1": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-coder-v2-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-0528": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-r1-basic": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-v3": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-v3-0324": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/deepseek-v3p1": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/firefunction-v2": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/glm-4p5": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/glm-5": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/glm-4p5-air": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gpt-oss-120b": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/gpt-oss-20b": ["fireworks"],
  "accounts/fireworks/models/kimi-k2p5": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/kimi-k2-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/llama-v3p1-405b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p1-8b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p2-11b-vision-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p2-1b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p2-3b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama-v3p2-90b-vision-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama4-maverick-instruct-basic": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/llama4-scout-instruct-basic": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/mixtral-8x22b-instruct-hf": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/qwen2-72b-instruct": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen2p5-coder-32b-instruct": [
    "fireworks",
  ],
  "fireworks_ai/accounts/fireworks/models/yi-large": ["fireworks"],
  "fireworks_ai/nomic-ai/nomic-embed-text-v1": ["fireworks"],
  "fireworks_ai/nomic-ai/nomic-embed-text-v1.5": ["fireworks"],
  "fireworks_ai/thenlper/gte-base": ["fireworks"],
  "fireworks_ai/thenlper/gte-large": ["fireworks"],
  "grok-3": ["xAI"],
  "grok-3-latest": ["xAI"],
  "grok-3-beta": ["xAI"],
  "grok-3-fast-beta": ["xAI"],
  "grok-3-fast-latest": ["xAI"],
  "grok-3-mini": ["xAI"],
  "grok-3-mini-latest": ["xAI"],
  "grok-3-mini-fast": ["xAI"],
  "grok-3-mini-fast-latest": ["xAI"],
  "grok-3-mini-beta": ["xAI"],
  "grok-3-mini-fast-beta": ["xAI"],
  "grok-code-fast-1": ["xAI"],
  "grok-code-fast": ["xAI"],
  "grok-code-fast-1-0825": ["xAI"],
  "gemini-3.1-pro-preview": ["google"],
  "gemini-3.1-pro-preview-customtools": ["google"],
  "gemini-3.1-flash-lite-preview": ["google"],
  "gemini-3-pro-image-preview": ["google"],
  "gemini-3-flash-preview": ["google"],
  "publishers/google/models/gemini-3.1-pro-preview": ["vertex"],
  "publishers/google/models/gemini-3.1-pro-preview-customtools": ["vertex"],
  "publishers/google/models/gemini-3.1-flash-lite-preview": ["vertex"],
  "publishers/google/models/gemini-3-pro-preview": ["vertex"],
  "publishers/google/models/gemini-3-flash-preview": ["vertex"],
  "publishers/google/models/gemini-3-pro-image-preview": ["vertex"],
  "publishers/google/models/gemini-2.5-pro": ["vertex"],
  "publishers/google/models/gemini-2.5-pro-preview-05-06": ["vertex"],
  "publishers/google/models/gemini-2.5-pro-preview-03-25": ["vertex"],
  "publishers/google/models/gemini-2.5-pro-exp-03-25": ["vertex"],
  "publishers/google/models/gemini-2.5-flash": ["vertex"],
  "publishers/google/models/gemini-2.5-flash-preview-05-20": ["vertex"],
  "publishers/google/models/gemini-2.5-flash-preview-04-17": ["vertex"],
  "publishers/google/models/gemini-2.5-flash-lite": ["vertex"],
  "publishers/google/models/gemini-2.5-flash-lite-preview-06-17": ["vertex"],
  "publishers/google/models/gemini-2.0-flash-thinking-exp-01-21": ["vertex"],
  "publishers/google/models/gemini-2.0-flash": ["vertex"],
  "publishers/google/models/gemini-2.0-flash-001": ["vertex"],
  "publishers/google/models/gemini-2.0-flash-lite": ["vertex"],
  "publishers/google/models/gemini-2.0-flash-lite-001": ["vertex"],
  "publishers/google/models/gemini-2.0-flash-lite-preview-02-05": ["vertex"],
  "publishers/google/models/gemini-1.5-pro": ["vertex"],
  "publishers/google/models/gemini-1.5-pro-002": ["vertex"],
  "publishers/google/models/gemini-1.5-pro-001": ["vertex"],
  "publishers/google/models/gemini-1.5-flash": ["vertex"],
  "publishers/google/models/gemini-1.5-flash-002": ["vertex"],
  "publishers/google/models/gemini-1.5-flash-001": ["vertex"],
  "publishers/google/models/gemini-1.0-pro-vision": ["vertex"],
  "publishers/google/models/gemini-1.0-pro-vision-001": ["vertex"],
  "publishers/google/models/gemini-1.0-pro": ["vertex"],
  "publishers/google/models/gemini-1.0-pro-002": ["vertex"],
  "publishers/google/models/gemini-1.0-pro-001": ["vertex"],
  "publishers/meta/models/llama-3.3-70b-instruct-maas": ["vertex"],
  "publishers/meta/models/llama-3.2-90b-vision-instruct-maas": ["vertex"],
  "publishers/meta/models/llama-3.1-401b-instruct-maas": ["vertex"],
  "publishers/meta/models/llama-3.1-70b-instruct-maas": ["vertex"],
  "publishers/meta/models/llama-3.1-8b-instruct-maas": ["vertex"],
  "publishers/mistralai/models/mistral-large-2411": ["vertex"],
  "publishers/mistralai/models/mistral-nemo": ["vertex"],
  "publishers/mistralai/models/codestral-2501": ["vertex"],
  "publishers/qwen/models/qwen3-235b-a22b-instruct-2507-maas": ["vertex"],
  "publishers/anthropic/models/claude-sonnet-4-6": ["vertex"],
  "publishers/anthropic/models/claude-sonnet-4-5": ["vertex"],
  "publishers/anthropic/models/claude-sonnet-4-5@20250929": ["vertex"],
  "publishers/anthropic/models/claude-sonnet-4": ["vertex"],
  "publishers/anthropic/models/claude-sonnet-4@20250514": ["vertex"],
  "publishers/anthropic/models/claude-3-7-sonnet": ["vertex"],
  "publishers/anthropic/models/claude-3-7-sonnet@20250219": ["vertex"],
  "publishers/anthropic/models/claude-haiku-4-5": ["vertex"],
  "publishers/anthropic/models/claude-haiku-4-5@20251001": ["vertex"],
  "publishers/anthropic/models/claude-3-5-haiku": ["vertex"],
  "publishers/anthropic/models/claude-3-5-haiku@20241022": ["vertex"],
  "publishers/anthropic/models/claude-3-5-sonnet-v2": ["vertex"],
  "publishers/anthropic/models/claude-3-5-sonnet-v2@20241022": ["vertex"],
  "publishers/anthropic/models/claude-3-5-sonnet": ["vertex"],
  "publishers/anthropic/models/claude-3-5-sonnet@20240620": ["vertex"],
  "publishers/anthropic/models/claude-opus-4-7": ["vertex"],
  "publishers/anthropic/models/claude-opus-4-6": ["vertex"],
  "publishers/anthropic/models/claude-opus-4-5@20251101": ["vertex"],
  "publishers/anthropic/models/claude-opus-4-1@20250805": ["vertex"],
  "publishers/anthropic/models/claude-opus-4": ["vertex"],
  "publishers/anthropic/models/claude-opus-4@20250514": ["vertex"],
  "publishers/anthropic/models/claude-3-opus": ["vertex"],
  "publishers/anthropic/models/claude-3-opus@20240229": ["vertex"],
  "publishers/anthropic/models/claude-3-haiku": ["vertex"],
  "publishers/anthropic/models/claude-3-haiku@20240307": ["vertex"],
  "databricks-claude-3-7-sonnet": ["databricks"],
  "databricks-meta-llama-3-3-70b-instruct": ["databricks"],
  "databricks-meta-llama-3-1-405b-instruct": ["databricks"],
  "databricks-meta-llama-3-1-8b-instruct": ["databricks"],
  "openai/gpt-oss-120b": ["together", "groq", "baseten"],
  "openai/gpt-oss-20b": ["groq"], // NOTE: We use groq pricing for this and Together pricing for the 120B model
  "accounts/fireworks/models/gpt-oss-120b": ["fireworks"],
  "accounts/fireworks/models/gpt-oss-20b": ["fireworks"],
  "gpt-oss-120b": ["cerebras"],
  "Qwen3-Coder-480B-A35B-Instruct": ["baseten"],
  "moonshotai/Kimi-K2-Instruct": ["baseten"],
  "deepseek-ai/DeepSeek-V3-0324": ["baseten"],
  "publishers/moonshotai/models/kimi-k2.5": ["azure"],
  "fireworks_ai/accounts/fireworks/models/glm-4p7": ["fireworks"],
  "fireworks_ai/accounts/fireworks/models/qwen3-vl-30b-a3b-instruct": [
    "fireworks",
  ],
};

export function getModelEndpointTypes(model: string): ModelEndpointType[] {
  return (
    AvailableEndpointTypes[model] ||
    (getAvailableModels()[model] &&
      DefaultEndpointTypes[getAvailableModels()[model].format]) ||
    []
  );
}

export const AISecretTypes: { [keyName: string]: ModelEndpointType } = {
  OPENAI_API_KEY: "openai",
  ANTHROPIC_API_KEY: "anthropic",
  GEMINI_API_KEY: "google",
  MISTRAL_API_KEY: "mistral",
  TOGETHER_API_KEY: "together",
  FIREWORKS_API_KEY: "fireworks",
  PERPLEXITY_API_KEY: "perplexity",
  XAI_API_KEY: "xAI",
  GROQ_API_KEY: "groq",
  LEPTON_API_KEY: "lepton",
  CEREBRAS_API_KEY: "cerebras",
  REPLICATE_API_KEY: "replicate",
  BASETEN_API_KEY: "baseten",
};

export const CloudSecretTypes: { [keyName: string]: ModelEndpointType } = {
  AWS_DEFAULT_CREDENTIALS: "bedrock",
  GOOGLE_DEFAULT_CREDENTIALS: "vertex",
  AZURE_DEFAULT_CREDENTIALS: "azure",
  DATABRICKS_DEFAULT_CREDENTIALS: "databricks",
};

export const EndpointProviderToBaseURL: {
  [name in ModelEndpointType]: string | null;
} = {
  openai: "https://api.openai.com/v1",
  braintrust: null,
  anthropic: "https://api.anthropic.com/v1",
  perplexity: "https://api.perplexity.ai",
  replicate: "https://openai-proxy.replicate.com/v1",
  together: "https://api.together.xyz/v1",
  google: "https://generativelanguage.googleapis.com/v1beta",
  mistral: "https://api.mistral.ai/v1",
  ollama: "http://127.0.0.1:11434/v1",
  groq: "https://api.groq.com/openai/v1",
  lepton: "https://<model>.lepton.run/api/v1/", // As far as I can tell, this works for all models
  fireworks: "https://api.fireworks.ai/inference/v1",
  baseten: "https://inference.baseten.co/v1",
  cerebras: "https://api.cerebras.ai/v1",
  xAI: "https://api.x.ai/v1",
  bedrock: null,
  vertex: null,
  azure: null,
  databricks: null,
  js: null,
};

export function buildClassicChatPrompt(messages: Message[]) {
  return (
    messages
      .map(
        ({ content, role }) => `<|im_start|>${role}
${content}<|im_end|>`,
      )
      .join("\n") + "\n<|im_start|>assistant"
  );
}

export function translateParams(
  toProvider: ModelFormat,
  params: Record<string, unknown>,
  modelSpec?: ModelSpec | null,
): Record<string, unknown> {
  let translatedParams: Record<string, unknown> = {};

  for (const [k, v] of Object.entries(params || {})) {
    const safeValue = v ?? undefined; // Don't propagate "null" along
    const translatedKey = modelParamToModelParam[k as keyof ModelParams] as
      | keyof ModelParams
      | undefined
      | null;

    if (translatedKey === null) {
      continue;
    }

    const hasDefaultParam =
      translatedKey !== undefined &&
      Object.prototype.hasOwnProperty.call(
        defaultModelParamSettings[toProvider] ?? {},
        translatedKey,
      );

    translatedParams[hasDefaultParam ? translatedKey : k] = safeValue;
  }

  // ideally we should short circuit and just have a master mapper but this avoids scope
  // for now
  const mapper = paramMappers[toProvider];
  if (mapper) {
    translatedParams = mapper(
      translatedParams as unknown as OpenAIChatCompletionCreateParams,
      modelSpec,
    ) as unknown as Record<string, unknown>;
  }

  return translatedParams;
}

export const anthropicSupportedMediaTypes = [
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
];

export const anthropicTextBlockSchema = z.object({
  type: z.literal("text").optional(),
  text: z.string().default(""),
});
export const anthropicImageBlockSchema = z.object({
  type: z.literal("image").optional(),
  source: z.object({
    type: z.enum(["base64"]).optional(),
    media_type: z.enum(["image/jpeg", "image/png", "image/gif", "image/webp"]),
    data: z.string().default(""),
  }),
});
const anthropicContentBlockSchema = z.union([
  anthropicTextBlockSchema,
  anthropicImageBlockSchema,
]);
const anthropicContentBlocksSchema = z.array(anthropicContentBlockSchema);
const anthropicContentSchema = z.union([
  z.string().default(""),
  anthropicContentBlocksSchema,
]);

export type AnthropicImageBlock = z.infer<typeof anthropicImageBlockSchema>;
export type AnthropicContent = z.infer<typeof anthropicContentSchema>;
