import { z } from "zod";

export const PromptInputs = ["chat", "completion"] as const;
export type PromptInputType = (typeof PromptInputs)[number];

export const ModelFormats = [
  "openai",
  "anthropic",
  "google",
  "window",
  "js",
  "converse",
] as const;
export type ModelFormat = (typeof ModelFormats)[number];

export const ModelSchema = z.object({
  format: z.enum(ModelFormats),
  flavor: z.enum(PromptInputs),
  multimodal: z.boolean().nullish(),
  input_cost_per_token: z.number().nullish(),
  output_cost_per_token: z.number().nullish(),
  input_cost_per_mil_tokens: z.number().nullish(),
  output_cost_per_mil_tokens: z.number().nullish(),
  displayName: z.string().nullish(),
  o1_like: z.boolean().nullish(),
  experimental: z.boolean().nullish(),
});

export type ModelSpec = z.infer<typeof ModelSchema>;

export const AvailableModels: { [name: string]: ModelSpec } = {
  // OPENAI / AZURE MODELS
  "gpt-4o": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 2.5,
    output_cost_per_mil_tokens: 10,
    displayName: "GPT-4o",
  },
  "gpt-4o-2024-11-20": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 2.5,
    output_cost_per_mil_tokens: 10,
  },
  "gpt-4o-2024-08-06": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 2.5,
    output_cost_per_mil_tokens: 10,
  },
  "gpt-4o-2024-05-13": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 5,
    output_cost_per_mil_tokens: 15,
  },
  "chatgpt-4o-latest": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 2.5,
    output_cost_per_mil_tokens: 10,
  },
  "gpt-4o-mini": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.6,
    displayName: "GPT-4o mini",
  },
  "gpt-4o-mini-2024-07-18": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.6,
  },
  o1: {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 15.0,
    output_cost_per_mil_tokens: 60,
    o1_like: true,
  },
  "o1-2024-12-17": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 15.0,
    output_cost_per_mil_tokens: 60,
    o1_like: true,
  },
  "o1-mini": {
    format: "openai",
    flavor: "chat",
    multimodal: false,
    input_cost_per_mil_tokens: 3.0,
    output_cost_per_mil_tokens: 12.0,
    o1_like: true,
  },
  "o1-mini-2024-09-12": {
    format: "openai",
    flavor: "chat",
    multimodal: false,
    input_cost_per_mil_tokens: 3.0,
    output_cost_per_mil_tokens: 12.0,
    o1_like: true,
  },
  "o1-preview": {
    format: "openai",
    flavor: "chat",
    multimodal: false,
    input_cost_per_mil_tokens: 15.0,
    output_cost_per_mil_tokens: 60,
    o1_like: true,
  },
  "o1-preview-2024-09-12": {
    format: "openai",
    flavor: "chat",
    multimodal: false,
    input_cost_per_mil_tokens: 15.0,
    output_cost_per_mil_tokens: 60.0,
    o1_like: true,
  },
  "o3-mini": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 1.1,
    output_cost_per_mil_tokens: 4.4,
    o1_like: true,
  },
  "o3-mini-2025-01-31": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 1.1,
    output_cost_per_mil_tokens: 4.4,
    o1_like: true,
  },
  "gpt-4-turbo": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 10,
    output_cost_per_mil_tokens: 30,
    displayName: "GPT-4 Turbo",
  },
  "gpt-4-turbo-2024-04-09": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 10,
    output_cost_per_mil_tokens: 30,
  },
  "gpt-4-turbo-preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 10,
    output_cost_per_mil_tokens: 30,
  },
  "gpt-4-0125-preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 10,
    output_cost_per_mil_tokens: 30,
  },
  "gpt-4-1106-preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 10,
    output_cost_per_mil_tokens: 30,
  },
  "gpt-4": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 30,
    output_cost_per_mil_tokens: 60,
    displayName: "GPT-4",
  },
  "gpt-4-0613": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 30,
    output_cost_per_mil_tokens: 60,
  },
  "gpt-4-0314": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 30,
    output_cost_per_mil_tokens: 60,
  },
  "gpt-3.5-turbo-0125": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.5,
    output_cost_per_mil_tokens: 1.5,
    displayName: "GPT 3.5T 0125",
  },
  "gpt-3.5-turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.5,
    output_cost_per_mil_tokens: 1.5,
    displayName: "GPT 3.5T",
  },
  "gpt-35-turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.5,
    output_cost_per_mil_tokens: 1.5,
    displayName: "GPT 3.5T",
  },
  "gpt-3.5-turbo-1106": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 2,
    displayName: "GPT 3.5T 1106",
  },
  "gpt-3.5-turbo-instruct": {
    format: "openai",
    flavor: "completion",
    input_cost_per_mil_tokens: 1.5,
    output_cost_per_mil_tokens: 2,
    displayName: "GPT 3.5T Instruct",
  },
  "gpt-3.5-turbo-instruct-0914": {
    format: "openai",
    flavor: "completion",
    input_cost_per_mil_tokens: 1.5,
    output_cost_per_mil_tokens: 2,
    displayName: "GPT 3.5T Instruct 0914",
  },
  "gpt-4-32k": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 60,
    output_cost_per_mil_tokens: 120,
    displayName: "GPT 4 32k",
  },
  "gpt-4-32k-0613": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 60,
    output_cost_per_mil_tokens: 120,
    displayName: "GPT 4 32k 0613",
  },
  "gpt-4-32k-0314": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 60,
    output_cost_per_mil_tokens: 120,
    displayName: "GPT 4 32k 0314",
  },
  "gpt-4-vision-preview": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 10,
    output_cost_per_mil_tokens: 30,
    displayName: "GPT 4 Vision-Preview",
  },
  "gpt-4-1106-vision-preview": {
    format: "openai",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 10,
    output_cost_per_mil_tokens: 30,
    displayName: "GPT 4 1106 Vision-Preview",
  },
  "gpt-3.5-turbo-16k": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 4,
    displayName: "GPT 3.5T 16k",
  },
  "gpt-35-turbo-16k": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 4,
    displayName: "GPT 3.5T 16k",
  },
  "gpt-3.5-turbo-16k-0613": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 4,
    displayName: "GPT 3.5T 16k 0613",
  },
  "gpt-3.5-turbo-0613": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.5,
    output_cost_per_mil_tokens: 2,
    displayName: "GPT 3.5T 0613",
  },
  "gpt-3.5-turbo-0301": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.5,
    output_cost_per_mil_tokens: 2,
    displayName: "GPT 3.5T 0301",
  },
  "text-davinci-003": {
    format: "openai",
    flavor: "completion",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 2,
    displayName: "Text Davinci 003",
  },

  // ANTHROPIC MODELS
  "claude-3-5-sonnet-latest": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
    displayName: "Claude 3.5 Sonnet",
  },
  "claude-3-5-sonnet-20241022": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
  },
  "claude-3-5-sonnet-20240620": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
  },
  "claude-3-5-haiku-latest": {
    format: "anthropic",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 5,
    displayName: "Claude 3.5 Haiku",
  },
  "claude-3-5-haiku-20241022": {
    format: "anthropic",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 5,
  },
  "claude-3-opus-latest": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 15,
    output_cost_per_mil_tokens: 75,
    displayName: "Claude 3 Opus",
  },
  "claude-3-opus-20240229": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 15,
    output_cost_per_mil_tokens: 75,
  },
  "claude-3-sonnet-latest": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
    displayName: "Claude 3 Sonnet",
  },
  "claude-3-sonnet-20240229": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
  },
  "claude-3-haiku-latest": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.25,
    output_cost_per_mil_tokens: 1.25,
    displayName: "Claude 3 Haiku",
  },
  "claude-3-haiku-20240307": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.25,
    output_cost_per_mil_tokens: 1.25,
  },
  "claude-instant-1.2": {
    format: "anthropic",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 2.4,
    displayName: "Claude Instant 1.2",
  },
  "claude-instant-1": {
    format: "anthropic",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 2.4,
    displayName: "Claude Instant 1",
  },
  "claude-2.1": {
    format: "anthropic",
    flavor: "chat",
    input_cost_per_mil_tokens: 8,
    output_cost_per_mil_tokens: 24,
    displayName: "Claude 2.1",
  },
  "claude-2.0": {
    format: "anthropic",
    flavor: "chat",
    input_cost_per_mil_tokens: 8,
    output_cost_per_mil_tokens: 24,
    displayName: "Claude 2.0",
  },
  "claude-2": {
    format: "anthropic",
    flavor: "chat",
    input_cost_per_mil_tokens: 8,
    output_cost_per_mil_tokens: 24,
    displayName: "Claude 2",
  },

  // REPLICATE MODELS
  "meta/llama-2-70b-chat": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.65,
    output_cost_per_mil_tokens: 2.75,
    displayName: "LLaMA 2 70b Chat",
  },

  // OLLAMA MODELS
  mistral: {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.0,
    output_cost_per_mil_tokens: 0.0,
    displayName: "Mistral",
  },
  phi: {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.0,
    output_cost_per_mil_tokens: 0.0,
    displayName: "Phi",
  },

  // PERPLEXITY MODELS
  "pplx-7b-chat": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.07,
    output_cost_per_mil_tokens: 0.28,
    displayName: "Perplexity 7b Chat",
  },
  "pplx-7b-online": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Perplexity 7b Online",
  },
  "pplx-70b-chat": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.7,
    output_cost_per_mil_tokens: 2.8,
    displayName: "Perplexity 70b Chat",
  },
  "pplx-70b-online": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 1,
    displayName: "Perplexity 70b Online",
  },
  "codellama-34b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.35,
    output_cost_per_mil_tokens: 1.4,
    displayName: "Code Llama 34b Instruct",
  },
  "codellama-70b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.7,
    output_cost_per_mil_tokens: 2.8,
    displayName: "Code Llama 70b Instruct",
  },
  "llama-3-8b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "LLaMA 3 8b Instruct",
  },
  "llama-3-70b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 1,
    displayName: "LLaMA 3 70b Instruct",
  },
  "llama-2-13b-chat": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.14,
    output_cost_per_mil_tokens: 0.56,
    displayName: "LLaMA 2 13b Chat",
  },
  "llama-2-70b-chat": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 1,
    displayName: "LLaMA 2 70b Chat",
  },
  "mistral-7b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.07,
    output_cost_per_mil_tokens: 0.28,
    displayName: "Mistral 7b Instruct",
  },
  "mixtral-8x7b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.07,
    output_cost_per_mil_tokens: 0.28,
    displayName: "Mixtral 8x7B Instruct",
  },
  "mixtral-8x22b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 1,
    displayName: "Mixtral 8x22B Instruct",
  },
  "openhermes-2-mistral-7b": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "OpenHermes 2",
  },
  "openhermes-2.5-mistral-7b": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "OpenHermes 2.5",
  },

  // TOGETHER MODELS
  // Together Meta.
  "meta-llama/Llama-3.3-70B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.88,
    output_cost_per_mil_tokens: 0.88,
    displayName: "Llama 3.3 70B Instruct Turbo",
  },
  "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.0,
    output_cost_per_mil_tokens: 0.0,
    displayName: "Llama 3.3 70B Instruct Turbo Free",
  },
  "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.2,
    output_cost_per_mil_tokens: 1.2,
    displayName: "Llama 3.2 90B Vision Instruct Turbo",
    multimodal: true,
  },
  "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.18,
    output_cost_per_mil_tokens: 0.18,
    displayName: "Llama 3.2 11B Vision Instruct Turbo",
    multimodal: true,
  },
  "meta-llama/Llama-Vision-Free": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.0,
    output_cost_per_mil_tokens: 0.0,
    displayName: "Llama Vision Free",
    multimodal: true,
  },
  "meta-llama/Llama-3.2-3B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.06,
    output_cost_per_mil_tokens: 0.06,
    displayName: "Llama 3.2 3B Instruct Turbo",
  },
  "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 3.5,
    output_cost_per_mil_tokens: 3.5,
    displayName: "Llama 3.1 405B Instruct Turbo",
  },
  "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.88,
    output_cost_per_mil_tokens: 0.88,
    displayName: "Llama 3.1 70B Instruct Turbo",
  },
  "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.18,
    output_cost_per_mil_tokens: 0.18,
    displayName: "Llama 3.1 8B Instruct Turbo",
  },
  "meta-llama/Llama-3-70b-chat-hf": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
    displayName: "Llama 3 70B Instruct Reference",
  },
  "meta-llama/Meta-Llama-3-70B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.88,
    output_cost_per_mil_tokens: 0.88,
    displayName: "Llama 3 70B Instruct Turbo",
  },
  "meta-llama/Meta-Llama-3-70B-Instruct-Lite": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.54,
    output_cost_per_mil_tokens: 0.54,
    displayName: "Llama 3 70B Instruct Lite",
  },
  "meta-llama/Llama-3-8b-chat-hf": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Llama 3 8B Instruct Reference",
  },
  "meta-llama/Meta-Llama-3-8B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.18,
    output_cost_per_mil_tokens: 0.18,
    displayName: "Llama 3 8B Instruct Turbo",
  },
  "meta-llama/Meta-Llama-3-8B-Instruct-Lite": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
    displayName: "Llama 3 8B Instruct Lite",
  },

  // Together Gemma.
  "google/gemma-2-27b-it": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 0.8,
    displayName: "Gemma-2 Instruct (27B)",
  },
  "google/gemma-2-9b-it": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.3,
    output_cost_per_mil_tokens: 0.3,
    displayName: "Gemma-2 Instruct (9B)",
  },
  "google/gemma-2b-it": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
    displayName: "Gemma Instruct (2B)",
  },

  // Together Mistral.
  "mistralai/Mistral-Small-24B-Instruct-2501": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 0.8,
    displayName: "Mistral Small (24B) Instruct 25.01",
  },
  "mistralai/Mistral-7B-Instruct-v0.3": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Mistral (7B) Instruct v0.3",
  },
  "mistralai/Mistral-7B-Instruct-v0.2": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Mistral (7B) Instruct v0.2",
  },
  "mistralai/Mistral-7B-Instruct-v0.1": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Mistral (7B) Instruct",
  },
  "mistralai/Mixtral-8x22B-Instruct-v0.1": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.2,
    output_cost_per_mil_tokens: 1.2,
    displayName: "Mixtral 8x22B Instruct v0.1",
  },
  "mistralai/Mixtral-8x7B-Instruct-v0.1": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.6,
    output_cost_per_mil_tokens: 0.6,
    displayName: "Mixtral 8x7B Instruct v0.1",
  },

  // Together DeepSeek.
  "deepseek-ai/DeepSeek-V3": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.25,
    output_cost_per_mil_tokens: 1.25,
    displayName: "DeepSeek V3",
  },
  "deepseek-ai/DeepSeek-R1": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 7,
    output_cost_per_mil_tokens: 7,
    displayName: "DeepSeek R1",
  },
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 2,
    displayName: "DeepSeek R1 Distill Llama 70B",
  },
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B-Free": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0,
    output_cost_per_mil_tokens: 0,
    displayName: "DeepSeek R1 Distill Llama 70B Free",
  },
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.6,
    output_cost_per_mil_tokens: 1.6,
    displayName: "DeepSeek R1 Distill Qwen 14B",
  },
  "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.18,
    output_cost_per_mil_tokens: 0.18,
    displayName: "DeepSeek R1 Distill Qwen 1.5B",
  },
  "deepseek-ai/deepseek-llm-67b-chat": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
    displayName: "DeepSeek LLM Chat (67B)",
  },

  // Together Qwen.
  "Qwen/Qwen2.5-72B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.2,
    output_cost_per_mil_tokens: 1.2,
    displayName: "Qwen 2.5 72B Instruct Turbo",
  },
  "Qwen/Qwen2.5-7B-Instruct-Turbo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.3,
    output_cost_per_mil_tokens: 0.3,
    displayName: "Qwen 2.5 7B Instruct Turbo",
  },
  "Qwen/Qwen2.5-Coder-32B-Instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 0.8,
    displayName: "Qwen 2.5 Coder 32B Instruct",
  },
  "Qwen/QwQ-32B-Preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 0.8,
    displayName: "Qwen QwQ 32B Preview",
  },
  "Qwen/Qwen2-VL-72B-Instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.2,
    output_cost_per_mil_tokens: 1.2,
    displayName: "Qwen-2VL (72B) Instruct",
  },
  "Qwen/Qwen2-72B-Instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
    displayName: "Qwen 2 Instruct (72B)",
  },

  // Together deprecated.
  "meta-llama/Meta-Llama-3-70B": {
    format: "openai",
    flavor: "completion",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
    displayName: "Llama 3 70b",
  },
  "meta-llama/Llama-3-8b-hf": {
    format: "openai",
    flavor: "completion",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Llama 3 8b HF",
  },
  "meta-llama/Llama-2-70b-chat-hf": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
    displayName: "Llama 2 70b Chat HF",
  },
  "deepseek-ai/deepseek-coder-33b-instruct": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 0.8,
    displayName: "Deepseek Coder 33b Instruct",
  },
  "NousResearch/Nous-Hermes-2-Yi-34B": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 0.8,
    displayName: "Nous Hermes 2 Yi 34B",
  },
  "mistralai/mixtral-8x7b-32kseqlen": {
    format: "openai",
    flavor: "completion",
    input_cost_per_mil_tokens: 0.06,
    output_cost_per_mil_tokens: 0.06,
    displayName: "Mixtral 8x7B 32k",
  },
  "mistralai/Mixtral-8x7B-Instruct-v0.1-json": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.6,
    output_cost_per_mil_tokens: 0.6,
    displayName: "Mixtral 8x7B Instruct v0.1 JSON",
  },
  "mistralai/Mixtral-8x22B": {
    format: "openai",
    flavor: "completion",
    input_cost_per_mil_tokens: 1.08,
    output_cost_per_mil_tokens: 1.08,
    displayName: "Mixtral 8x22B",
  },

  // MISTRAL MODELS
  "mistral-large-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 6,
    displayName: "Mistral Large",
  },
  "mistral-large-2411": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 6,
  },
  "pixtral-large-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 6,
    displayName: "Pixtral Large",
    multimodal: true,
  },
  "pixtral-large-2411": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 6,
    multimodal: true,
  },
  "mistral-small-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.3,
    displayName: "Mistral Small",
  },
  "mistral-small-2501": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.3,
  },
  "codestral-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.3,
    output_cost_per_mil_tokens: 0.9,
    displayName: "Codestral",
  },
  "codestral-2501": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.3,
    output_cost_per_mil_tokens: 0.9,
  },
  "ministral-8b-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
    displayName: "Ministral 8B",
  },
  "ministral-8b-2410": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
  },
  "ministral-3b-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.04,
    output_cost_per_mil_tokens: 0.04,
    displayName: "Ministral 3B",
  },
  "ministral-3b-2410": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.04,
    output_cost_per_mil_tokens: 0.04,
  },
  "pixtral-12b-2409": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.15,
    displayName: "Pixtral 12B",
    multimodal: true,
  },
  "open-mistral-nemo": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.15,
    displayName: "Mistral NeMo",
  },
  "open-mistral-nemo-2407": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.15,
  },
  "open-codestral-mamba": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.6,
    output_cost_per_mil_tokens: 0.6,
    displayName: "Codestral Mamba",
  },
  // Mistral deprecated.
  // "mistral-embed": {
  //   format: "openai",
  //   flavor: "chat",
  //   input_cost_per_mil_tokens: 0.1,
  //   output_cost_per_mil_tokens: 0.1,
  //   displayName: "Mistral Embed",
  // },
  "open-mixtral-8x22b": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 6,
    displayName: "Mixtral 8x22B",
  },
  "mistral-tiny": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.46,
    displayName: "Mistral Tiny",
  },
  "mistral-small": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 3,
    displayName: "Mistral Small",
  },
  "mistral-medium": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2.75,
    output_cost_per_mil_tokens: 8.1,
    displayName: "Mistral Medium",
  },

  // GROQ MODELS
  "llama-3.3-70b-versatile": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.59,
    output_cost_per_mil_tokens: 0.79,
    displayName: "Llama 3.3 70B Versatile 128k",
  },
  "llama-3.1-8b-instant": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.05,
    output_cost_per_mil_tokens: 0.08,
    displayName: "Llama 3.1 8B Instant 128k",
  },
  "llama3-70b-8192": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.64,
    output_cost_per_mil_tokens: 0.8,
    displayName: "Llama 3 70B 8k",
  },
  "llama3-8b-8192": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
    displayName: "Llama 3 8B 8k",
  },
  "gemma2-9b-it": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Gemma 2 9B",
  },
  "mixtral-8x7b-32768": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.27,
    output_cost_per_mil_tokens: 0.27,
    displayName: "Mixtral 8x7B 32k",
  },
  // Groq experimental.
  "deepseek-r1-distill-llama-70b": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.23,
    output_cost_per_mil_tokens: 0.69,
    displayName: "DeepSeek R1 Distill Llama 70b",
    experimental: true,
  },
  "llama-3.3-70b-specdec": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.59,
    output_cost_per_mil_tokens: 0.99,
    displayName: "Llama 3.3 70B SpecDec 8k",
    experimental: true,
  },
  "llama-3.2-90b-vision-preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
    displayName: "Llama 3.2 90B Vision 8k (Preview)",
    multimodal: true,
    experimental: true,
  },
  "llama-3.2-11b-vision-preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.18,
    output_cost_per_mil_tokens: 0.18,
    displayName: "Llama 3.2 11B Vision 8k (Preview)",
    multimodal: true,
    experimental: true,
  },
  "llama-3.2-3b-preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.06,
    output_cost_per_mil_tokens: 0.06,
    displayName: "Llama 3.2 3B (Preview) 8k",
    experimental: true,
  },
  "llama-3.2-1b-preview": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.04,
    output_cost_per_mil_tokens: 0.04,
    displayName: "Llama 3.2 1B (Preview) 8k",
    experimental: true,
  },
  // Groq deprecated.
  "gemma-7b-it": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
    displayName: "Gemma 7b IT",
  },
  "llama-3.1-70b-versatile": {
    format: "openai",
    flavor: "chat",
    displayName: "LLaMA 3.1 70b Versatile",
  },
  "llama-3.1-405b-reasoning": {
    format: "openai",
    flavor: "chat",
    displayName: "LLaMA 3.1 405b Reasoning",
  },
  "llama2-70b-4096": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.7,
    output_cost_per_mil_tokens: 0.8,
    displayName: "LLaMA 2 70b 4096",
  },

  // LEPTON MODELS
  "llama3-1-8b": {
    format: "openai",
    flavor: "chat",
    displayName: "LLaMA 3.1 8b",
    input_cost_per_mil_tokens: 0.07,
    output_cost_per_mil_tokens: 0.07,
  },
  "llama3-1-70b": {
    format: "openai",
    flavor: "chat",
    displayName: "LLaMA 3.1 70b",
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 0.8,
  },
  "llama3-1-405b": {
    format: "openai",
    flavor: "chat",
    displayName: "LLaMA 3.1 405b",
    input_cost_per_mil_tokens: 2.8,
    output_cost_per_mil_tokens: 2.8,
  },

  // FIREWORKS MODELS
  "accounts/fireworks/models/llama-v3p3-70b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.3 70B Instruct",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
  },
  "accounts/fireworks/models/llama-v3p2-90b-vision-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.2 90B Vision Instruct",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
    multimodal: true,
  },
  "accounts/fireworks/models/llama-v3p2-11b-vision-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.2 11B Vision Instruct",
    input_cost_per_mil_tokens: 0.18,
    output_cost_per_mil_tokens: 0.18,
    multimodal: true,
  },
  "accounts/fireworks/models/llama-v3p2-3b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.2 3B Instruct",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
  },
  "accounts/fireworks/models/llama-v3p1-405b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.1 405B Instruct",
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 3,
  },
  "accounts/fireworks/models/llama-v3p1-405b-instruct-long": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.1 405B Instruct Long",
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 3,
  },
  "accounts/fireworks/models/llama-v3p1-70b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.1 70B Instruct",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
  },
  "accounts/fireworks/models/llama-v3p1-8b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.1 8B Instruct",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.2,
  },
  "accounts/fireworks/models/mistral-small-24b-instruct-2501": {
    format: "openai",
    flavor: "chat",
    displayName: "Mistral Small 3 Instruct",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
  },
  "accounts/fireworks/models/mixtral-8x22b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Mixtral MoE 8x22B Instruct",
    input_cost_per_mil_tokens: 1.2,
    output_cost_per_mil_tokens: 1.2,
  },
  "accounts/fireworks/models/mixtral-8x7b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Mixtral MoE 8x7B Instruct",
    input_cost_per_mil_tokens: 0.5,
    output_cost_per_mil_tokens: 0.5,
  },
  "accounts/fireworks/models/deepseek-v3": {
    format: "openai",
    flavor: "chat",
    displayName: "DeepSeek V3",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
  },
  "accounts/fireworks/models/deepseek-r1": {
    format: "openai",
    flavor: "chat",
    displayName: "DeepSeek R1",
    input_cost_per_mil_tokens: 8,
    output_cost_per_mil_tokens: 8,
  },
  "accounts/fireworks/models/qwen2p5-72b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Qwen2.5 72B Instruct",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
  },
  "accounts/fireworks/models/qwen2p5-coder-32b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Qwen2.5 Coder 32B Instruct",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
  },
  "accounts/fireworks/models/qwen-qwq-32b-preview": {
    format: "openai",
    flavor: "chat",
    displayName: "Qwen QwQ 32B Preview",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
  },
  "accounts/fireworks/models/qwen2-vl-72b-instruct": {
    format: "openai",
    flavor: "chat",
    displayName: "Qwen2 VL 72B Instruct",
    input_cost_per_mil_tokens: 0.9,
    output_cost_per_mil_tokens: 0.9,
  },

  // CEREBRAS MODELS
  "llama3.3-70b": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.3 70B",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
  },
  "llama3.1-8b": {
    format: "openai",
    flavor: "chat",
    displayName: "Llama 3.1 8B",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
  },

  // GEMINI MODELS
  "gemini-2.0-flash-001": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.4,
    displayName: "Gemini 2.0 Flash",
    multimodal: true,
  },
  "gemini-2.0-flash-lite-preview-02-05": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.075,
    output_cost_per_mil_tokens: 0.3,
    displayName: "Gemini 2.0 Flash Lite",
    multimodal: true,
  },
  "gemini-1.5-flash": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.075,
    output_cost_per_mil_tokens: 0.3,
    displayName: "Gemini 1.5 Flash",
    multimodal: true,
  },
  "gemini-1.5-flash-latest": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.075,
    output_cost_per_mil_tokens: 0.3,
    multimodal: true,
  },
  "gemini-1.5-flash-001": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.075,
    output_cost_per_mil_tokens: 0.3,
    multimodal: true,
  },
  "gemini-1.5-flash-002": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.075,
    output_cost_per_mil_tokens: 0.3,
    multimodal: true,
  },
  "gemini-1.5-flash-8b": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.0375,
    output_cost_per_mil_tokens: 0.15,
    displayName: "Gemini 1.5 Flash-8B",
    multimodal: true,
  },
  "gemini-1.5-flash-8b-latest": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.0375,
    output_cost_per_mil_tokens: 0.15,
    multimodal: true,
  },
  "gemini-1.5-flash-8b-001": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.0375,
    output_cost_per_mil_tokens: 0.15,
    multimodal: true,
  },
  "gemini-1.5-pro": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.25,
    output_cost_per_mil_tokens: 5.0,
    displayName: "Gemini 1.5 Pro",
    multimodal: true,
  },
  "gemini-1.5-pro-latest": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.25,
    output_cost_per_mil_tokens: 5.0,
    multimodal: true,
  },
  "gemini-1.5-pro-001": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.25,
    output_cost_per_mil_tokens: 5.0,
    multimodal: true,
  },
  "gemini-1.5-pro-002": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.25,
    output_cost_per_mil_tokens: 5.0,
    multimodal: true,
  },
  "gemini-2.0-pro-exp-02-05": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0, // TODO: Appears to be free for now?
    output_cost_per_mil_tokens: 0,
    displayName: "Gemini 2.0 Pro",
    multimodal: true,
  },
  // Gemini experimental.
  "gemini-2.0-flash-thinking-exp-01-21": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0, // TODO: Appears to be free for now?
    output_cost_per_mil_tokens: 0,
    displayName: "Gemini 2.0 Flash Thinking",
    multimodal: true,
    experimental: true,
  },
  "gemini-2.0-flash-exp": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0, // TODO: Appears to be free for now?
    output_cost_per_mil_tokens: 0,
    multimodal: true,
    experimental: true,
  },
  "gemini-exp-1206": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0, // TODO: Appears to be free for now?
    output_cost_per_mil_tokens: 0,
    multimodal: true,
    experimental: true,
  },
  // Gemini deprecated.
  "gemini-1.0-pro": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.5,
    output_cost_per_mil_tokens: 1.5,
    displayName: "Gemini 1.0 Pro",
  },
  "gemini-pro": {
    format: "google",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.25,
    output_cost_per_mil_tokens: 0.5,
    displayName: "Gemini Pro",
  },

  // XAI MODELS
  "grok-2-vision": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 10,
    multimodal: true,
    displayName: "Grok 2 Vision",
  },
  "grok-2-vision-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 10,
    multimodal: true,
  },
  "grok-2-vision-1212": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 10,
    multimodal: true,
  },
  "grok-2": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 10,
    displayName: "Grok 2",
  },
  "grok-2-latest": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 10,
  },
  "grok-2-1212": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 2,
    output_cost_per_mil_tokens: 10,
  },
  "grok-vision-beta": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 5,
    output_cost_per_mil_tokens: 15,
    multimodal: true,
  },
  "grok-beta": {
    format: "openai",
    flavor: "chat",
    input_cost_per_mil_tokens: 5,
    output_cost_per_mil_tokens: 15,
  },

  // BEDROCK MODELS
  "amazon.nova-micro-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.035,
    output_cost_per_mil_tokens: 0.14,
    displayName: "Nova Micro",
  },
  "amazon.titan-text-premier-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.5,
    output_cost_per_mil_tokens: 1.5,
    displayName: "Titan Text Premier",
  },
  "amazon.titan-text-express-v1": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.2,
    output_cost_per_mil_tokens: 0.6,
    displayName: "Titan Text Express",
  },
  "amazon.titan-text-lite-v1": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Titan Text Lite",
  },
  "anthropic.claude-3-5-sonnet-20241022-v2:0": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
    displayName: "Claude 3.5 Sonnet v2",
  },
  "anthropic.claude-3-5-sonnet-20240620-v1:0": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
    displayName: "Claude 3.5 Sonnet",
  },
  "anthropic.claude-3-5-haiku-20241022-v1:0": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 4,
    displayName: "Claude 3.5 Haiku",
  },
  "anthropic.claude-3-opus-20240229-v1:0": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 15,
    output_cost_per_mil_tokens: 75,
    displayName: "Claude 3 Opus",
  },
  "anthropic.claude-3-sonnet-20240229-v1:0": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
    displayName: "Claude 3 Sonnet",
  },
  "anthropic.claude-3-haiku-20240307-v1:0": {
    format: "anthropic",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.25,
    output_cost_per_mil_tokens: 1.25,
    displayName: "Claude 3 Haiku",
  },
  "amazon.nova-pro-v1:0": {
    format: "converse",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.8,
    output_cost_per_mil_tokens: 3.2,
    displayName: "Nova Pro",
  },
  "amazon.nova-lite-v1:0": {
    format: "converse",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.06,
    output_cost_per_mil_tokens: 0.24,
    displayName: "Nova Lite",
  },
  "us.meta.llama3-3-70b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.72,
    output_cost_per_mil_tokens: 0.72,
    displayName: "Llama 3.3 70B Instruct",
  },
  "us.meta.llama3-2-90b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.72,
    output_cost_per_mil_tokens: 0.72,
    displayName: "Llama 3.2 90B Vision Instruct",
  },
  "us.meta.llama3-2-11b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    multimodal: true,
    input_cost_per_mil_tokens: 0.16,
    output_cost_per_mil_tokens: 0.16,
    displayName: "Llama 3.2 11B Vision Instruct",
  },
  "us.meta.llama3-2-3b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.15,
    displayName: "Llama 3.2 3B Instruct",
  },
  "us.meta.llama3-2-1b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.1,
    output_cost_per_mil_tokens: 0.1,
    displayName: "Llama 3.2 1B Instruct",
  },
  "us.meta.llama3-1-70b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.72,
    output_cost_per_mil_tokens: 0.72,
    displayName: "Llama 3.1 70B Instruct",
  },
  "us.meta.llama3-1-8b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.22,
    output_cost_per_mil_tokens: 0.22,
    displayName: "Llama 3.1 8B Instruct",
  },
  "meta.llama3-70b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 2.65,
    output_cost_per_mil_tokens: 3.5,
    displayName: "Llama 3 70B Instruct",
  },
  "meta.llama3-8b-instruct-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.3,
    output_cost_per_mil_tokens: 0.6,
    displayName: "Llama 3 8B Instruct",
  },
  "mistral.mistral-large-2402-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 4,
    output_cost_per_mil_tokens: 12,
    displayName: "Mistral Large 24.02",
  },
  "mistral.mistral-small-2402-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 1,
    output_cost_per_mil_tokens: 3,
    displayName: "Mistral Small 24.02",
  },
  "mistral.mixtral-8x7b-instruct-v0:1": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.45,
    output_cost_per_mil_tokens: 0.7,
    displayName: "Mixtral 8x7B",
  },
  "mistral.mistral-7b-instruct-v0:2": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.15,
    output_cost_per_mil_tokens: 0.2,
    displayName: "Mistral 7B",
  },
  "cohere.command-r-plus-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 3,
    output_cost_per_mil_tokens: 15,
    displayName: "Command R+",
  },
  "cohere.command-r-v1:0": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.5,
    output_cost_per_mil_tokens: 1.5,
    displayName: "Command R",
  },
  "cohere.command-text-v14": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 1.5,
    output_cost_per_mil_tokens: 2,
    displayName: "Command",
  },
  "cohere.command-light-text-v14": {
    format: "converse",
    flavor: "chat",
    input_cost_per_mil_tokens: 0.3,
    output_cost_per_mil_tokens: 0.6,
    displayName: "Command Light",
  },

  "text-block": {
    format: "js",
    flavor: "completion",
    displayName: "Text-block",
  },
};
